// Impromptu deck. Row: [word, type, Thai meaning, speaking idea (links the word to cabin crew), Thai translation]
(window.VOCAB_GROUPS = window.VOCAB_GROUPS || []).push(
["quality", [
["Teamwork","n.","การทำงานเป็นทีม","Teamwork means we help each other. No crew member can run a flight alone.","ทีมเวิร์กคือการช่วยกัน ไม่มีลูกเรือคนไหนดูแลเที่ยวบินคนเดียวได้"],
["Responsibility","n.","ความรับผิดชอบ","Responsibility means I finish my job well. Crew are responsible for every passenger's safety.","ความรับผิดชอบคือทำงานของตัวเองให้ดี ลูกเรือรับผิดชอบความปลอดภัยของผู้โดยสารทุกคน"],
["Leadership","n.","ภาวะผู้นำ","A good leader helps the team, not only gives orders. In an emergency, crew must lead passengers.","ผู้นำที่ดีช่วยทีม ไม่ใช่แค่สั่ง ในเหตุฉุกเฉินลูกเรือต้องนำผู้โดยสาร"],
["Management","n.","การจัดการ","Management means using time and things well. Crew manage service in a short flight.","การจัดการคือใช้เวลาและของให้ดี ลูกเรือจัดการบริการในเที่ยวบินสั้น"],
["Time management","n.","การบริหารเวลา","On a short flight to Samui, good time management helps us serve everyone.","ในเที่ยวบินสั้นไปสมุย การบริหารเวลาที่ดีช่วยให้บริการได้ครบทุกคน"],
["Communication","n.","การสื่อสาร","Good communication is clear and kind. It keeps the team and passengers safe.","การสื่อสารที่ดีต้องชัดเจนและสุภาพ ช่วยให้ทีมและผู้โดยสารปลอดภัย"],
["Patience","n.","ความอดทน","Patience means I stay calm and wait. Tired passengers need patient crew.","ความอดทนคือใจเย็นและรอได้ ผู้โดยสารที่เหนื่อยต้องการลูกเรือที่ใจเย็น"],
["Flexibility","n.","ความยืดหยุ่น","Flight plans can change any time, so crew must be flexible.","แผนการบินเปลี่ยนได้ตลอด ลูกเรือจึงต้องยืดหยุ่น"],
["Adaptability","n.","ความสามารถในการปรับตัว","I moved from a lab to service work. I can adapt to new places and people.","ฉันเคยย้ายจากงานแล็บมางานบริการ จึงปรับตัวกับที่ใหม่และคนใหม่ได้"],
["Empathy","n.","ความเข้าอกเข้าใจ","Empathy means I feel what others feel. It helps me care for a nervous passenger.","คือการเข้าใจความรู้สึกคนอื่น ช่วยให้ดูแลผู้โดยสารที่กังวลได้"],
["Honesty","n.","ความซื่อสัตย์","Honesty means telling the truth, even about my mistakes. Passengers trust honest crew.","คือการพูดความจริงแม้เป็นความผิดของตัวเอง ผู้โดยสารไว้ใจลูกเรือที่ซื่อสัตย์"],
["Integrity","n.","ความซื่อตรง","Integrity means doing the right thing when nobody is watching, like following safety rules.","คือการทำสิ่งที่ถูกแม้ไม่มีใครเห็น เช่น การทำตามกฎความปลอดภัย"],
["Discipline","n.","ระเบียบวินัย","Discipline means following rules every day. I learned it from factory work.","วินัยคือการทำตามกฎทุกวัน ฉันเรียนรู้จากงานโรงงาน"],
["Punctuality","n.","การตรงต่อเวลา","If one crew member is late, the whole flight is late. So punctuality is respect.","ถ้าลูกเรือสายคนเดียว ทั้งเที่ยวบินก็ช้า การตรงเวลาจึงเป็นการให้เกียรติ"],
["Reliability","n.","ความไว้วางใจได้","A reliable person does what they say. The team can count on me.","คนที่ไว้ใจได้คือคนที่ทำตามที่พูด ทีมพึ่งพาฉันได้"],
["Positive attitude","n.","ทัศนคติเชิงบวก","A positive attitude makes hard days easier, for me and for my team.","ทัศนคติบวกทำให้วันที่ยากง่ายขึ้น ทั้งกับฉันและทีม"],
["Hospitality","n.","การต้อนรับขับสู้","Hospitality means making guests feel at home. Thai people are famous for it.","คือการทำให้แขกรู้สึกเหมือนอยู่บ้าน คนไทยขึ้นชื่อเรื่องนี้"],
["Service mind","n.","จิตบริการ","Service mind means I am happy to help. I learned it at Swensen's and the tea shop.","จิตบริการคือเต็มใจช่วยเหลือ ฉันเรียนรู้จาก Swensen's และร้านชา"],
["Problem-solving","n.","การแก้ปัญหา","In R&D I solve problems every day. Onboard, crew must solve problems quickly too.","ในงาน R&D ฉันแก้ปัญหาทุกวัน บนเครื่องลูกเรือก็ต้องแก้ปัญหาให้เร็ว"],
["Decision-making","n.","การตัดสินใจ","Crew must decide fast and think of safety first.","ลูกเรือต้องตัดสินใจเร็วและคิดถึงความปลอดภัยก่อน"],
["Calmness","n.","ความสงบนิ่ง","When crew are calm, passengers feel safe.","เมื่อลูกเรือสงบ ผู้โดยสารก็รู้สึกปลอดภัย"],
["Confidence","n.","ความมั่นใจ","Confidence comes from practice. Confident crew make passengers trust them.","ความมั่นใจมาจากการฝึก ลูกเรือที่มั่นใจทำให้ผู้โดยสารไว้ใจ"],
["Respect","n.","ความเคารพ","Respect means treating everyone well, from every country and culture.","ความเคารพคือการปฏิบัติดีกับทุกคน ทุกประเทศและวัฒนธรรม"],
["Kindness","n.","ความมีน้ำใจ","Kindness is free, but people remember it for a long time.","น้ำใจไม่มีต้นทุน แต่คนจำได้นาน"],
["Attention to detail","n.","ความใส่ใจรายละเอียด","In R&D one small mistake changes the product. Boutique service is also about small details.","ใน R&D ผิดนิดเดียวสินค้าก็เปลี่ยน บริการแบบ boutique ก็อยู่ที่รายละเอียดเล็ก ๆ"],
["Safety","n.","ความปลอดภัย","Safety comes first, in a food factory and on an aircraft.","ความปลอดภัยมาก่อน ทั้งในโรงงานอาหารและบนเครื่องบิน"],
["Cultural awareness","n.","ความเข้าใจวัฒนธรรม","Passengers come from many countries. Understanding their culture helps me serve them well.","ผู้โดยสารมาจากหลายประเทศ การเข้าใจวัฒนธรรมช่วยให้บริการได้ดี"],
["Grooming","n.","การดูแลบุคลิกและการแต่งกาย","Good grooming shows respect for passengers and for the airline.","การแต่งกายเรียบร้อยแสดงความเคารพต่อผู้โดยสารและสายการบิน"],
["Professionalism","n.","ความเป็นมืออาชีพ","Professionalism means doing my best even on a bad day.","มืออาชีพคือทำให้ดีที่สุดแม้ในวันที่แย่"],
["Smile","n.","รอยยิ้ม","A smile is the first service. It works in every language.","รอยยิ้มคือบริการแรก และใช้ได้กับทุกภาษา"]
]],
["food", [
["Coffee","n.","กาแฟ","Coffee wakes people up. Crew are like coffee, because they bring energy to the cabin.","กาแฟทำให้คนตื่น ลูกเรือก็เหมือนกาแฟที่เติมพลังให้ห้องโดยสาร"],
["Tea","n.","ชา","Tea makes people calm. I worked at a tea shop, and I learned that every customer likes it differently.","ชาทำให้ใจสงบ ฉันเคยทำร้านชาและรู้ว่าลูกค้าแต่ละคนชอบไม่เหมือนกัน"],
["Bubble tea","n.","ชานมไข่มุก","Bubble tea has many parts that mix well, like a good team. I made it every day at the tea shop.","ชานมไข่มุกมีหลายส่วนที่เข้ากันดีเหมือนทีมที่ดี ฉันทำทุกวันที่ร้านชา"],
["Ice cream","n.","ไอศกรีม","Ice cream makes people smile. At Swensen's I learned to serve fast before it melts.","ไอศกรีมทำให้คนยิ้ม ที่ Swensen's ฉันเรียนรู้ที่จะเสิร์ฟให้เร็วก่อนละลาย"],
["Fruit","n.","ผลไม้","Fruit is fresh and healthy. I work with fruit every day in R&D, and I know each one is different, like passengers.","ผลไม้สดและดีต่อสุขภาพ ฉันทำงานกับผลไม้ทุกวัน แต่ละชนิดต่างกันเหมือนผู้โดยสาร"],
["Mango sticky rice","n.","ข้าวเหนียวมะม่วง","Mango and sticky rice are different but perfect together, like a good crew team.","มะม่วงกับข้าวเหนียวต่างกันแต่เข้ากันดี เหมือนทีมลูกเรือที่ดี"],
["Breakfast","n.","อาหารเช้า","Breakfast starts the day. A warm welcome from crew starts a good trip.","อาหารเช้าคือจุดเริ่มของวัน การต้อนรับที่อบอุ่นคือจุดเริ่มของการเดินทางที่ดี"],
["Street food","n.","อาหารริมทาง","Street food is fast, tasty and friendly. It shows Thai service mind.","อาหารริมทางเร็ว อร่อย และเป็นกันเอง สะท้อนจิตบริการแบบไทย"],
["Thai food","n.","อาหารไทย","Thai food has many tastes in one dish. Crew also need many skills in one person.","อาหารไทยมีหลายรสในจานเดียว ลูกเรือก็ต้องมีหลายทักษะในคนเดียว"],
["Dessert","n.","ของหวาน","Dessert is the happy ending of a meal. A warm goodbye is the happy ending of a flight.","ของหวานคือตอนจบที่ดีของมื้ออาหาร คำอำลาที่อบอุ่นคือตอนจบที่ดีของเที่ยวบิน"],
["Water","n.","น้ำ","Water is simple, but everyone needs it. Good service is the same.","น้ำเป็นของเรียบง่ายแต่ทุกคนต้องการ บริการที่ดีก็เช่นกัน"],
["Healthy food","n.","อาหารเพื่อสุขภาพ","Healthy food gives us energy. Crew need a healthy body for long flights.","อาหารดีให้พลังงาน ลูกเรือต้องมีร่างกายแข็งแรงสำหรับเที่ยวบินยาว"]
]],
["fruit", [
["Apple","n.","แอปเปิล","An apple a day keeps the doctor away. Crew also take care of health every day.","แอปเปิลวันละผลทำให้ห่างไกลหมอ ลูกเรือก็ต้องดูแลสุขภาพทุกวัน"],
["Banana","n.","กล้วย","A banana is easy to eat and gives quick energy. Good service should be easy and quick too.","กล้วยกินง่ายและให้พลังงานเร็ว บริการที่ดีก็ควรง่ายและเร็ว"],
["Orange","n.","ส้ม","An orange has many small parts in one fruit, like many crew in one team.","ส้มมีหลายกลีบในผลเดียว เหมือนลูกเรือหลายคนในทีมเดียว"],
["Mango","n.","มะม่วง","Mango is the king of Thai fruit. Tourists love it, and I use it a lot in my R&D work.","มะม่วงคือราชาผลไม้ไทย นักท่องเที่ยวชอบมาก และฉันใช้บ่อยในงาน R&D"],
["Pineapple","n.","สับปะรด","A pineapple has many eyes. Crew also need many eyes to watch the cabin.","สับปะรดมีตาเยอะ ลูกเรือก็ต้องมีตารอบด้านเพื่อดูแลห้องโดยสาร"],
["Watermelon","n.","แตงโม","Watermelon is fresh on a hot day. Crew make tired passengers feel fresh again.","แตงโมสดชื่นในวันร้อน ลูกเรือทำให้ผู้โดยสารที่เหนื่อยสดชื่นขึ้น"],
["Grape","n.","องุ่น","Grapes grow together in one bunch. They remind me of teamwork.","องุ่นอยู่รวมกันเป็นพวง ทำให้นึกถึงทีมเวิร์ก"],
["Strawberry","n.","สตรอว์เบอร์รี","A strawberry is small but makes a cake special. Small details make service special.","สตรอว์เบอร์รีลูกเล็กแต่ทำให้เค้กพิเศษ รายละเอียดเล็ก ๆ ทำให้บริการพิเศษ"],
["Coconut","n.","มะพร้าว","Every part of a coconut is useful, like a team member who helps in every role. Samui is famous for coconuts.","ทุกส่วนของมะพร้าวมีประโยชน์ เหมือนคนในทีมที่ช่วยได้ทุกหน้าที่ สมุยขึ้นชื่อเรื่องมะพร้าว"],
["Papaya","n.","มะละกอ","Papaya makes som tam, a dish everyone shares. Sharing is part of teamwork.","มะละกอใช้ทำส้มตำ อาหารที่ทุกคนแบ่งกันกิน การแบ่งปันคือส่วนหนึ่งของทีมเวิร์ก"],
["Lemon","n.","เลมอน","When life gives you lemons, make lemonade. Crew turn problems into good service.","เมื่อชีวิตให้เลมอนมา ก็ทำน้ำเลมอน ลูกเรือเปลี่ยนปัญหาให้เป็นบริการที่ดี"],
["Lime","n.","มะนาว","A little lime makes Thai food perfect. A small touch can make service perfect.","มะนาวนิดเดียวทำให้อาหารไทยกลมกล่อม ความใส่ใจเล็ก ๆ ทำให้บริการสมบูรณ์"],
["Kiwi","n.","กีวี","A kiwi looks plain outside but is bright inside. We should not judge people by their look.","กีวีข้างนอกธรรมดาแต่ข้างในสดใส เราไม่ควรตัดสินคนจากภายนอก"],
["Peach","n.","ลูกพีช","A peach is soft, so we handle it with care. We handle passengers with care too.","ลูกพีชนุ่ม ต้องจับอย่างเบามือ เราก็ดูแลผู้โดยสารอย่างใส่ใจ"],
["Cherry","n.","เชอร์รี","The cherry on top makes a dessert special. A smile is the cherry on top of service.","เชอร์รีบนยอดทำให้ของหวานพิเศษ รอยยิ้มคือเชอร์รีของงานบริการ"],
["Blueberry","n.","บลูเบอร์รี","A blueberry is tiny but very healthy. Small actions can have big value.","บลูเบอร์รีลูกเล็กแต่มีประโยชน์มาก การกระทำเล็ก ๆ ก็มีค่ามาก"],
["Durian","n.","ทุเรียน","Durian is strong outside and sweet inside, like crew who stay strong but kind.","ทุเรียนแข็งข้างนอก หวานข้างใน เหมือนลูกเรือที่เข้มแข็งแต่ใจดี"],
["Mangosteen","n.","มังคุด","Mangosteen is the queen of fruit. It is pure white inside, like an honest heart.","มังคุดคือราชินีผลไม้ ข้างในขาวสะอาดเหมือนใจที่ซื่อสัตย์"],
["Rambutan","n.","เงาะ","Rambutan looks hairy and strange, but it is sweet. First looks can be wrong.","เงาะดูมีขนแปลก ๆ แต่หวาน สิ่งที่เห็นครั้งแรกอาจไม่ใช่ทั้งหมด"],
["Longan","n.","ลำไย","Longan is a small, sweet fruit from the north. It reminds me of warm Thai hospitality.","ลำไยเป็นผลไม้ลูกเล็กหวานจากภาคเหนือ ทำให้นึกถึงน้ำใจแบบไทย"],
["Lychee","n.","ลิ้นจี่","Lychee has a hard skin but a soft heart, like crew who are strict about safety but gentle.","ลิ้นจี่เปลือกแข็งแต่เนื้อนุ่ม เหมือนลูกเรือที่เข้มเรื่องความปลอดภัยแต่อ่อนโยน"],
["Dragon fruit","n.","แก้วมังกร","Dragon fruit has a bright colour that people notice. Crew also give a bright first impression.","แก้วมังกรสีสดใสสะดุดตา ลูกเรือก็สร้างความประทับใจแรกที่สดใส"],
["Jackfruit","n.","ขนุน","Jackfruit is very big, and many people share it. Good things are better when shared.","ขนุนลูกใหญ่และแบ่งกันกินได้หลายคน ของดีจะยิ่งดีเมื่อแบ่งปัน"],
["Guava","n.","ฝรั่ง","Guava is simple, cheap and healthy. Good service does not need to be expensive.","ฝรั่งเรียบง่าย ราคาถูก และมีประโยชน์ บริการที่ดีไม่จำเป็นต้องแพง"],
["Passion fruit","n.","เสาวรส","I made a passion fruit base in my R&D job. Its name reminds me to work with passion.","ฉันเคยทำฟรุ๊ตเบสเสาวรสในงาน R&D ชื่อของมันเตือนให้ทำงานด้วยใจรัก"],
["Pomegranate","n.","ทับทิม","A pomegranate has hundreds of seeds inside. One flight has hundreds of stories too.","ทับทิมมีเมล็ดเป็นร้อยข้างใน หนึ่งเที่ยวบินก็มีเรื่องราวเป็นร้อยเช่นกัน"],
["Tamarind","n.","มะขาม","Tamarind is sweet and sour, like work. Some days are hard, but I still enjoy it.","มะขามมีทั้งหวานและเปรี้ยวเหมือนการทำงาน บางวันยากแต่ก็ยังสนุก"],
["Rose apple","n.","ชมพู่","Rose apple is light and full of water. It makes people fresh, like a cool towel onboard.","ชมพู่เบาและฉ่ำน้ำ ทำให้สดชื่นเหมือนผ้าเย็นบนเครื่อง"],
["Pomelo","n.","ส้มโอ","A pomelo takes time to peel, but it is worth it. Good things need patience.","ส้มโอต้องใช้เวลาปอกแต่คุ้มค่า ของดีต้องใช้ความอดทน"],
["Avocado","n.","อะโวคาโด","Avocado goes well with many dishes. Flexible crew can work well with anyone.","อะโวคาโดเข้ากับอาหารได้หลายอย่าง ลูกเรือที่ยืดหยุ่นก็ทำงานกับใครก็ได้"]
]],
["daily", [
["Morning","n.","ตอนเช้า","A good morning starts a good day. I wake up early, so I am never late.","เช้าที่ดีเริ่มต้นวันที่ดี ฉันตื่นเช้าจึงไม่เคยสาย"],
["Weekend","n.","วันหยุดสุดสัปดาห์","Most people rest on weekends, but crew work, because that is when people travel.","คนส่วนใหญ่พักวันเสาร์อาทิตย์ แต่ลูกเรือทำงานเพราะเป็นเวลาที่คนเดินทาง"],
["Sleep","n.","การนอนหลับ","Good sleep gives me energy and a real smile. Crew must plan their sleep well.","การนอนที่ดีให้พลังและรอยยิ้มที่สดใส ลูกเรือต้องวางแผนการนอนให้ดี"],
["Alarm clock","n.","นาฬิกาปลุก","An alarm clock helps me be on time. For crew, on time means on duty.","นาฬิกาปลุกช่วยให้ตรงเวลา สำหรับลูกเรือ ตรงเวลาคือหน้าที่"],
["Mobile phone","n.","โทรศัพท์มือถือ","A phone connects people far away. An airline connects people too.","โทรศัพท์เชื่อมคนที่อยู่ไกลกัน สายการบินก็เชื่อมผู้คนเช่นกัน"],
["Social media","n.","โซเชียลมีเดีย","On social media, one bad review goes far. So every passenger matters.","ในโซเชียล รีวิวแย่ครั้งเดียวไปได้ไกล ผู้โดยสารทุกคนจึงสำคัญ"],
["Money","n.","เงิน","Money is important, but a happy customer is worth more.","เงินสำคัญ แต่ลูกค้าที่มีความสุขมีค่ามากกว่า"],
["Shopping","n.","การซื้อของ","When I shop, I notice good and bad service. It teaches me how customers feel.","เวลาไปซื้อของ ฉันสังเกตบริการที่ดีและไม่ดี ทำให้เข้าใจความรู้สึกลูกค้า"],
["Cooking","n.","การทำอาหาร","Cooking needs the right steps and timing, like my R&D work and like cabin service.","การทำอาหารต้องมีขั้นตอนและจังหวะที่ถูก เหมือนงาน R&D และการบริการบนเครื่อง"],
["Cleaning","n.","การทำความสะอาด","A clean place is safe and comfortable. In my factory, hygiene comes first.","ที่สะอาดคือที่ปลอดภัยและสบาย ในโรงงานของฉันสุขอนามัยมาก่อน"],
["Traffic","n.","การจราจร","Bangkok traffic teaches me to plan and leave early.","รถติดในกรุงเทพฯ สอนให้ฉันวางแผนและออกเดินทางเร็ว"],
["Public transport","n.","ขนส่งสาธารณะ","Public transport takes many people safely to one place, just like an aircraft.","ขนส่งสาธารณะพาคนจำนวนมากไปถึงที่หมายอย่างปลอดภัย เหมือนเครื่องบิน"]
]],
["people", [
["Family","n.","ครอบครัว","My family supports my dream. A crew team is like a family in the sky.","ครอบครัวสนับสนุนความฝันของฉัน ทีมลูกเรือก็เหมือนครอบครัวบนฟ้า"],
["Mother","n.","แม่","My mother takes care of everyone before herself. She is my first teacher of service.","แม่ดูแลทุกคนก่อนตัวเอง แม่คือครูคนแรกเรื่องการบริการของฉัน"],
["Best friend","n.","เพื่อนสนิท","A best friend listens and tells the truth. I want to be that kind of teammate.","เพื่อนสนิทรับฟังและพูดความจริง ฉันอยากเป็นเพื่อนร่วมทีมแบบนั้น"],
["Teacher","n.","ครู","A good teacher is patient. Senior crew are teachers for new crew.","ครูที่ดีมีความอดทน ลูกเรือรุ่นพี่คือครูของลูกเรือใหม่"],
["Pet","n.","สัตว์เลี้ยง","A pet teaches us responsibility. We must take care of it every day.","สัตว์เลี้ยงสอนความรับผิดชอบ เราต้องดูแลทุกวัน"],
["Neighbor","n.","เพื่อนบ้าน","Good neighbors help each other. Passengers sit next to each other like neighbors.","เพื่อนบ้านที่ดีช่วยเหลือกัน ผู้โดยสารนั่งข้างกันก็เหมือนเพื่อนบ้าน"],
["Role model","n.","แบบอย่าง","My role model is a person who works hard and stays kind. I want to be a role model for new crew one day.","แบบอย่างของฉันคือคนที่ขยันและใจดี วันหนึ่งฉันอยากเป็นแบบอย่างให้ลูกเรือใหม่"]
]],
["nature", [
["Rain","n.","ฝน","Rain can delay a flight, but after rain the sky is clear. Problems always pass.","ฝนอาจทำให้เที่ยวบินล่าช้า แต่หลังฝนฟ้าก็ใส ปัญหาผ่านไปเสมอ"],
["Sun","n.","ดวงอาทิตย์","The sun gives light and warmth to everyone. Crew give warm service to every passenger.","ดวงอาทิตย์ให้แสงและความอบอุ่นกับทุกคน ลูกเรือก็ให้บริการที่อบอุ่นกับทุกคน"],
["Sea","n.","ทะเล","The sea is calm and wide. It reminds me of Samui and of staying calm.","ทะเลสงบและกว้าง ทำให้นึกถึงสมุยและการมีใจที่สงบ"],
["Mountain","n.","ภูเขา","A mountain is hard to climb, but the view is worth it, like my dream to be crew.","ภูเขาปีนยากแต่วิวคุ้มค่า เหมือนความฝันที่จะเป็นลูกเรือ"],
["Tree","n.","ต้นไม้","A tree grows slowly with strong roots. I want to grow in my career the same way.","ต้นไม้โตช้าแต่รากแข็งแรง ฉันอยากเติบโตในอาชีพแบบนั้น"],
["Flower","n.","ดอกไม้","A flower makes a room beautiful. A smile makes a cabin beautiful.","ดอกไม้ทำให้ห้องสวย รอยยิ้มทำให้ห้องโดยสารน่าอยู่"],
["Rainbow","n.","สายรุ้ง","A rainbow has many colours together, like crew and passengers from many countries.","สายรุ้งมีหลายสีอยู่ด้วยกัน เหมือนลูกเรือและผู้โดยสารจากหลายประเทศ"],
["Weather","n.","สภาพอากาศ","We cannot control the weather, but we can control how we act.","เราควบคุมอากาศไม่ได้ แต่ควบคุมการกระทำของตัวเองได้"],
["Season","n.","ฤดูกาล","Seasons change, and we adapt. Crew adapt to new places every day.","ฤดูกาลเปลี่ยนและเราก็ปรับตัว ลูกเรือปรับตัวกับที่ใหม่ทุกวัน"]
]],
["hobby", [
["Music","n.","ดนตรี","Music is a language everyone understands. It helps me relax after work.","ดนตรีคือภาษาที่ทุกคนเข้าใจ ช่วยให้ฉันผ่อนคลายหลังเลิกงาน"],
["Movie","n.","ภาพยนตร์","A good movie needs a whole team behind it. A good flight is the same.","หนังดีต้องมีทีมงานทั้งทีมอยู่เบื้องหลัง เที่ยวบินที่ดีก็เช่นกัน"],
["Exercise","n.","การออกกำลังกาย","Exercise keeps me strong. Crew need a strong body for long hours.","การออกกำลังกายทำให้แข็งแรง ลูกเรือต้องมีร่างกายที่ทนชั่วโมงทำงานยาว"],
["Reading","n.","การอ่าน","Reading opens my mind. Crew must keep learning new things.","การอ่านเปิดโลก ลูกเรือต้องเรียนรู้สิ่งใหม่อยู่เสมอ"],
["Photography","n.","การถ่ายภาพ","Photography teaches me to notice small details and beautiful moments.","การถ่ายภาพสอนให้สังเกตรายละเอียดเล็ก ๆ และช่วงเวลาที่สวยงาม"],
["Hobby","n.","งานอดิเรก","A hobby helps me rest, so I can come back to work with energy.","งานอดิเรกช่วยให้ได้พัก จะได้กลับไปทำงานอย่างมีพลัง"],
["Dream","n.","ความฝัน","My dream is to be cabin crew. A dream needs hard work to come true.","ความฝันของฉันคือการเป็นลูกเรือ ความฝันต้องใช้ความพยายามจึงจะเป็นจริง"],
["Happiness","n.","ความสุข","Happiness is making other people happy. That is why I love service.","ความสุขคือการทำให้คนอื่นมีความสุข ฉันจึงรักงานบริการ"]
]],
["abstract", [
["Success","n.","ความสำเร็จ","Success is not only for me. It is when my team and passengers are happy.","ความสำเร็จไม่ใช่ของฉันคนเดียว แต่คือเมื่อทีมและผู้โดยสารมีความสุข"],
["Failure","n.","ความล้มเหลว","In R&D many samples fail before one is good. Failure is a teacher.","ใน R&D ตัวอย่างหลายตัวไม่ผ่านก่อนจะได้ตัวที่ดี ความล้มเหลวคือครู"],
["Change","n.","การเปลี่ยนแปลง","I am changing from R&D to cabin crew. Change helps me grow.","ฉันกำลังเปลี่ยนจาก R&D มาเป็นลูกเรือ การเปลี่ยนแปลงทำให้เติบโต"],
["Mistake","n.","ความผิดพลาด","Everyone makes mistakes. The important thing is to say sorry, fix it and learn.","ทุกคนผิดพลาดได้ สิ่งสำคัญคือขอโทษ แก้ไข และเรียนรู้"],
["Challenge","n.","ความท้าทาย","A challenge makes me stronger. A new career is a big challenge that I am ready for.","ความท้าทายทำให้แข็งแกร่งขึ้น อาชีพใหม่คือความท้าทายที่ฉันพร้อม"],
["Goal","n.","เป้าหมาย","My goal is to wear the Bangkok Airways uniform. I work on it step by step.","เป้าหมายของฉันคือได้ใส่เครื่องแบบบางกอกแอร์เวย์ส ฉันทำทีละขั้น"],
["Opportunity","n.","โอกาส","This interview is an opportunity. I prepared well, so I can use it.","การสัมภาษณ์นี้คือโอกาส ฉันเตรียมตัวมาดีเพื่อคว้ามันไว้"],
["Gift","n.","ของขวัญ","The best gift is time and care. Good service is a gift to passengers.","ของขวัญที่ดีที่สุดคือเวลาและความใส่ใจ บริการที่ดีคือของขวัญสำหรับผู้โดยสาร"],
["First impression","n.","ความประทับใจแรก","We have only one chance for a first impression. For crew, it is the smile at the door.","ความประทับใจแรกมีโอกาสเดียว สำหรับลูกเรือคือรอยยิ้มที่ประตูเครื่อง"],
["Future","n.","อนาคต","The future comes from what I do today. Today I practise, and tomorrow I fly.","อนาคตมาจากสิ่งที่ทำวันนี้ วันนี้ฉันฝึก พรุ่งนี้ฉันบิน"]
]]
);
