(window.VOCAB_GROUPS = window.VOCAB_GROUPS || []).push(
["object", [
["Umbrella","n.","ร่ม","An umbrella protects us from rain and sun, like crew protect passengers' safety and comfort.","ร่มปกป้องเราจากฝนและแดด เหมือนลูกเรือปกป้องความปลอดภัยและความสบายของผู้โดยสาร"],
["Bag","n.","กระเป๋า","A bag carries what we need. Crew carry skills and a smile everywhere.","กระเป๋าใส่ของที่จำเป็น ลูกเรือพกทักษะและรอยยิ้มไปทุกที่"],
["Pen","n.","ปากกา","A pen is small, but crew always need one. Being ready is part of the job.","ปากกาเล็กแต่ลูกเรือต้องมีเสมอ ความพร้อมคือส่วนหนึ่งของงาน"],
["Mirror","n.","กระจก","A mirror shows the truth. I use it to check my grooming and my smile.","กระจกสะท้อนความจริง ฉันใช้ตรวจการแต่งกายและรอยยิ้ม"],
["Watch","n.","นาฬิกาข้อมือ","A watch reminds me that time is important. Crew must always be on time.","นาฬิกาเตือนว่าเวลาสำคัญ ลูกเรือต้องตรงเวลาเสมอ"],
["Key","n.","กุญแจ","A key opens a door. A smile is the key to a passenger's heart.","กุญแจเปิดประตู รอยยิ้มคือกุญแจสู่ใจผู้โดยสาร"],
["Shoes","n.","รองเท้า","Good shoes take us far. To understand passengers, I try to walk in their shoes.","รองเท้าดีพาเราไปได้ไกล และฉันพยายามมองจากมุมของผู้โดยสาร"],
["Book","n.","หนังสือ","A book gives knowledge. Crew study the safety manual like an important book.","หนังสือให้ความรู้ ลูกเรือศึกษาคู่มือความปลอดภัยเหมือนหนังสือเล่มสำคัญ"],
["Glasses","n.","แว่นตา","Glasses help us see clearly. Crew must see what passengers need.","แว่นช่วยให้มองชัด ลูกเรือต้องมองเห็นสิ่งที่ผู้โดยสารต้องการ"],
["Wallet","n.","กระเป๋าสตางค์","A wallet keeps valuable things safe. Crew keep passengers safe.","กระเป๋าสตางค์เก็บของมีค่าให้ปลอดภัย ลูกเรือดูแลผู้โดยสารให้ปลอดภัย"],
["Pillow","n.","หมอน","A pillow gives comfort. A small thing can make a passenger feel at home.","หมอนให้ความสบาย ของเล็ก ๆ ทำให้ผู้โดยสารรู้สึกเหมือนอยู่บ้าน"],
["Blanket","n.","ผ้าห่ม","A blanket keeps us warm. Offering one before a passenger asks is real care.","ผ้าห่มให้ความอบอุ่น การยื่นให้ก่อนผู้โดยสารขอคือความใส่ใจจริง"],
["Candle","n.","เทียน","A candle gives light to others. Service is giving to other people.","เทียนให้แสงสว่างแก่ผู้อื่น การบริการคือการให้"],
["Clock","n.","นาฬิกา","A clock never stops. Flights run on time because every team respects time.","นาฬิกาไม่เคยหยุด เที่ยวบินตรงเวลาเพราะทุกทีมเคารพเวลา"],
["Calendar","n.","ปฏิทิน","A calendar helps me plan. Crew plan their life around the flight schedule.","ปฏิทินช่วยวางแผน ลูกเรือวางแผนชีวิตตามตารางบิน"],
["Notebook","n.","สมุดบันทึก","I write what I learn in a notebook. In R&D I record every test.","ฉันจดสิ่งที่เรียนรู้ลงสมุด ในงาน R&D ฉันบันทึกทุกการทดลอง"],
["Pencil","n.","ดินสอ","With a pencil we can write, erase and try again. That is how we learn.","ดินสอเขียนได้ ลบได้ และลองใหม่ได้ นั่นคือการเรียนรู้"],
["Eraser","n.","ยางลบ","An eraser fixes mistakes. Crew fix problems quickly and politely.","ยางลบแก้ความผิดพลาด ลูกเรือแก้ปัญหาอย่างรวดเร็วและสุภาพ"],
["Scissors","n.","กรรไกร","Scissors have two blades that work together. Teamwork is the same.","กรรไกรมีสองใบมีดที่ทำงานด้วยกัน ทีมเวิร์กก็เช่นกัน"],
["Tape","n.","เทป","Tape holds things together. Good communication holds a team together.","เทปยึดของเข้าด้วยกัน การสื่อสารที่ดียึดทีมไว้ด้วยกัน"],
["Lipstick","n.","ลิปสติก","Lipstick is part of grooming. But a real smile is the most beautiful colour.","ลิปสติกเป็นส่วนหนึ่งของการแต่งหน้า แต่รอยยิ้มจริงใจสวยที่สุด"],
["Comb","n.","หวี","A comb keeps hair neat. Neat grooming shows respect for passengers.","หวีทำให้ผมเรียบร้อย การแต่งกายเรียบร้อยแสดงความเคารพต่อผู้โดยสาร"],
["Perfume","n.","น้ำหอม","Perfume leaves a good memory. Good service leaves a good memory too.","น้ำหอมทิ้งความทรงจำที่ดี บริการที่ดีก็เช่นกัน"],
["Toothbrush","n.","แปรงสีฟัน","We use a toothbrush every day. Good habits every day make a good crew member.","เราใช้แปรงสีฟันทุกวัน นิสัยที่ดีทุกวันสร้างลูกเรือที่ดี"],
["Towel","n.","ผ้าเช็ดตัว","A cool towel makes a tired passenger feel fresh. Small things matter.","ผ้าเย็นทำให้ผู้โดยสารที่เหนื่อยสดชื่น ของเล็ก ๆ มีความหมาย"],
["Soap","n.","สบู่","Soap keeps us clean. In my factory, clean hands are the first rule.","สบู่ทำให้สะอาด ในโรงงานของฉัน มือสะอาดคือกฎข้อแรก"],
["Chair","n.","เก้าอี้","A chair supports us. Crew support passengers all through the flight.","เก้าอี้รองรับเรา ลูกเรือคอยดูแลผู้โดยสารตลอดเที่ยวบิน"],
["Table","n.","โต๊ะ","A table brings people together to eat and talk. Service brings people together.","โต๊ะทำให้คนมานั่งกินและคุยกัน การบริการก็เชื่อมผู้คน"],
["Lamp","n.","โคมไฟ","A lamp gives light in the dark. Crew guide passengers in an emergency.","โคมไฟให้แสงในความมืด ลูกเรือนำทางผู้โดยสารในเหตุฉุกเฉิน"],
["Door","n.","ประตู","A door is the first and last thing passengers see. Crew welcome them and say goodbye there.","ประตูคือสิ่งแรกและสิ่งสุดท้ายที่ผู้โดยสารเห็น ลูกเรือต้อนรับและกล่าวลาที่นั่น"],
["Window","n.","หน้าต่าง","A window shows a new view. This job opens a window to the world for me.","หน้าต่างให้เห็นวิวใหม่ งานนี้เปิดหน้าต่างสู่โลกให้ฉัน"],
["Stairs","n.","บันได","We climb stairs one step at a time. I grow in my career step by step.","เราขึ้นบันไดทีละขั้น ฉันเติบโตในอาชีพทีละขั้นเช่นกัน"],
["Elevator","n.","ลิฟต์","An elevator takes people up. A good team lifts each other up.","ลิฟต์พาคนขึ้นไป ทีมที่ดีช่วยยกกันขึ้น"],
["Bicycle","n.","จักรยาน","To ride a bicycle, we must keep balance. Crew balance safety and service.","ขี่จักรยานต้องทรงตัว ลูกเรือต้องสมดุลระหว่างความปลอดภัยและการบริการ"],
["Camera","n.","กล้องถ่ายรูป","A camera keeps good memories. Crew help passengers make good travel memories.","กล้องเก็บความทรงจำดี ๆ ลูกเรือช่วยสร้างความทรงจำที่ดีในการเดินทาง"],
["Headphones","n.","หูฟัง","Headphones help us listen. Good crew listen before they speak.","หูฟังช่วยให้ฟัง ลูกเรือที่ดีฟังก่อนพูด"],
["Charger","n.","ที่ชาร์จ","A charger gives energy back. Rest and family are my charger.","ที่ชาร์จเติมพลัง การพักผ่อนและครอบครัวคือที่ชาร์จของฉัน"],
["Laptop","n.","แล็ปท็อป","I use a laptop to work and learn. Crew also learn new things all the time.","ฉันใช้แล็ปท็อปทำงานและเรียนรู้ ลูกเรือก็ต้องเรียนรู้สิ่งใหม่ตลอด"],
["Remote control","n.","รีโมต","A remote controls the TV. I cannot control others, but I can control my feelings.","รีโมตควบคุมทีวี ฉันควบคุมคนอื่นไม่ได้ แต่ควบคุมอารมณ์ตัวเองได้"],
["Light bulb","n.","หลอดไฟ","A light bulb means a new idea. In R&D I look for new ideas every day.","หลอดไฟหมายถึงไอเดียใหม่ ในงาน R&D ฉันหาไอเดียใหม่ทุกวัน"],
["Cup","n.","ถ้วย","An empty cup can take new things. I come to learn with an empty cup.","ถ้วยเปล่ารับของใหม่ได้ ฉันมาเรียนรู้ด้วยใจที่พร้อมรับ"],
["Spoon","n.","ช้อน","A spoon and fork work as a pair. Crew work in pairs and help each other.","ช้อนกับส้อมทำงานเป็นคู่ ลูกเรือก็ทำงานเป็นคู่และช่วยกัน"],
["Plate","n.","จาน","A clean plate shows care. How we serve is as important as the food.","จานสะอาดแสดงความใส่ใจ วิธีเสิร์ฟสำคัญพอกับอาหาร"],
["Bottle","n.","ขวด","A bottle keeps water safe inside. Rules keep people safe.","ขวดเก็บน้ำให้ปลอดภัย กฎช่วยให้คนปลอดภัย"],
["Ice cube","n.","น้ำแข็งก้อน","An ice cube cools a hot drink. Calm crew cool down a hot situation.","น้ำแข็งทำให้เครื่องดื่มเย็น ลูกเรือที่ใจเย็นทำให้สถานการณ์ร้อนเย็นลง"],
["Straw","n.","หลอดดูด","A straw is a small thing that makes drinking easy. Service is about small helpful things.","หลอดเป็นของเล็กที่ทำให้ดื่มง่าย การบริการคือสิ่งเล็ก ๆ ที่ช่วยคน"],
["Gift box","n.","กล่องของขวัญ","A gift box makes people excited. I want every flight to feel like a gift.","กล่องของขวัญทำให้คนตื่นเต้น ฉันอยากให้ทุกเที่ยวบินเป็นเหมือนของขวัญ"],
["Balloon","n.","ลูกโป่ง","A balloon goes up and makes children smile. Crew also bring joy in the sky.","ลูกโป่งลอยขึ้นและทำให้เด็กยิ้ม ลูกเรือก็นำความสุขมาบนฟ้า"],
["Seatbelt","n.","เข็มขัดนิรภัย","A seatbelt is simple, but it saves lives. Safety comes first.","เข็มขัดนิรภัยเรียบง่ายแต่ช่วยชีวิตได้ ความปลอดภัยมาก่อน"],
["Life jacket","n.","เสื้อชูชีพ","We hope we never use a life jacket, but we must always be ready.","เราหวังว่าจะไม่ต้องใช้เสื้อชูชีพ แต่ต้องพร้อมเสมอ"],
["Boarding pass","n.","บัตรขึ้นเครื่อง","A boarding pass is a ticket to a new place. Every passenger has a reason to fly.","บัตรขึ้นเครื่องคือตั๋วสู่ที่ใหม่ ผู้โดยสารทุกคนมีเหตุผลในการเดินทาง"],
["Trolley","n.","รถเข็น","The trolley brings food and drinks. Crew push it with care and a smile.","รถเข็นนำอาหารและเครื่องดื่มมา ลูกเรือเข็นด้วยความระวังและรอยยิ้ม"],
["Name tag","n.","ป้ายชื่อ","A name tag shows who I am. I want passengers to remember my name for good service.","ป้ายชื่อบอกว่าฉันคือใคร ฉันอยากให้ผู้โดยสารจำชื่อฉันได้จากบริการที่ดี"],
["Uniform","n.","เครื่องแบบ","A uniform shows we are one team. I would wear it with pride.","เครื่องแบบแสดงว่าเราคือทีมเดียวกัน ฉันจะสวมด้วยความภูมิใจ"]
]],
["travel", [
["Airport","n.","สนามบิน","An airport is where trips begin. Samui Airport looks like a garden resort.","สนามบินคือจุดเริ่มต้นการเดินทาง สนามบินสมุยดูเหมือนรีสอร์ตในสวน"],
["Passport","n.","หนังสือเดินทาง","A passport opens the world. It reminds me that passengers come from everywhere.","หนังสือเดินทางเปิดโลก และเตือนว่าผู้โดยสารมาจากทุกที่"],
["Suitcase","n.","กระเป๋าเดินทาง","We pack only important things in a suitcase. I pack my skills for this new job.","เราใส่แต่ของสำคัญลงกระเป๋า ฉันเตรียมทักษะสำหรับงานใหม่นี้"],
["Window seat","n.","ที่นั่งริมหน้าต่าง","A window seat has the best view. Crew help every passenger enjoy the trip.","ที่นั่งริมหน้าต่างวิวดีที่สุด ลูกเรือช่วยให้ทุกคนมีความสุขกับการเดินทาง"],
["Hotel","n.","โรงแรม","A good hotel makes guests feel at home. A boutique airline does the same in the sky.","โรงแรมที่ดีทำให้แขกรู้สึกเหมือนอยู่บ้าน สายการบิน boutique ก็ทำแบบนั้นบนฟ้า"],
["Holiday","n.","วันหยุดพักผ่อน","Many passengers fly for a holiday. Their holiday starts with our service.","ผู้โดยสารหลายคนบินไปพักผ่อน วันหยุดของเขาเริ่มที่บริการของเรา"],
["Beach","n.","ชายหาด","A beach makes people relax. I want passengers to feel relaxed on the flight too.","ชายหาดทำให้คนผ่อนคลาย ฉันอยากให้ผู้โดยสารผ่อนคลายบนเครื่องเช่นกัน"],
["Island","n.","เกาะ","An island needs a plane or a boat. Bangkok Airways connects islands like Samui to the world.","เกาะต้องไปด้วยเครื่องบินหรือเรือ บางกอกแอร์เวย์สเชื่อมเกาะอย่างสมุยกับโลก"],
["Koh Samui","n.","เกาะสมุย","Koh Samui has beautiful beaches and coconuts. Bangkok Airways built its airport there.","เกาะสมุยมีหาดสวยและมะพร้าว บางกอกแอร์เวย์สสร้างสนามบินที่นั่น"],
["Map","n.","แผนที่","A map shows the way. Crew show passengers the way to the exits.","แผนที่บอกทาง ลูกเรือบอกทางออกให้ผู้โดยสาร"],
["Souvenir","n.","ของที่ระลึก","A souvenir keeps a memory. A good flight is a souvenir in the heart.","ของที่ระลึกเก็บความทรงจำ เที่ยวบินที่ดีคือของที่ระลึกในใจ"],
["Jet lag","n.","อาการเมาเวลา","Jet lag makes us tired. Crew take care of their body with rest, water and exercise.","เจ็ตแล็กทำให้เหนื่อย ลูกเรือดูแลร่างกายด้วยการพัก น้ำ และการออกกำลังกาย"]
]],
["cartoon", [
["Doraemon","character","โดราเอมอน","Doraemon always has the right tool to help others, like crew who are ready for every situation.","โดราเอมอนมีของวิเศษช่วยคนอื่นเสมอ เหมือนลูกเรือที่พร้อมทุกสถานการณ์"],
["Nobita","character","โนบิตะ","Nobita is not perfect, but he has a kind heart and good friends who help him.","โนบิตะไม่สมบูรณ์แบบ แต่ใจดีและมีเพื่อนที่คอยช่วย"],
["Shin-chan","character","ชินจัง","Shin-chan is funny and makes people laugh. A little fun makes hard work lighter.","ชินจังตลกและทำให้คนหัวเราะ ความสนุกนิดหน่อยทำให้งานหนักเบาลง"],
["Pikachu","character","ปิกาจู","Pikachu is small but has big power, and he never leaves his friend.","ปิกาจูตัวเล็กแต่พลังเยอะ และไม่เคยทิ้งเพื่อน"],
["Hello Kitty","character","เฮลโลคิตตี้","Hello Kitty has no mouth, but everyone feels her kindness. Kindness needs no words.","คิตตี้ไม่มีปาก แต่ทุกคนรู้สึกถึงความน่ารัก ความใจดีไม่ต้องใช้คำพูด"],
["Snoopy","character","สนูปี้","Snoopy has a big imagination and is always happy. He reminds me to stay positive.","สนูปี้มีจินตนาการและมีความสุขเสมอ เตือนให้ฉันคิดบวก"],
["Mickey Mouse","character","มิกกี้เมาส์","Mickey Mouse welcomes everyone with a big smile, like crew at the aircraft door.","มิกกี้ต้อนรับทุกคนด้วยรอยยิ้มกว้าง เหมือนลูกเรือที่ประตูเครื่อง"],
["Winnie the Pooh","character","วินนี่เดอะพูห์","Pooh is kind and patient. He is a good example of service mind.","พูห์ใจดีและอดทน เป็นตัวอย่างที่ดีของจิตบริการ"],
["Elsa","character","เอลซ่า","Elsa learned to control her power. Crew learn to control their feelings.","เอลซ่าเรียนรู้ที่จะควบคุมพลัง ลูกเรือเรียนรู้ที่จะควบคุมอารมณ์"],
["Simba","character","ซิมบ้า","Simba ran away, but he came back to take responsibility.","ซิมบ้าเคยหนี แต่กลับมารับผิดชอบหน้าที่"],
["Nemo","character","นีโม่","Nemo never gives up, even when he is lost or has a big problem.","นีโม่ไม่ยอมแพ้ แม้หลงทางหรือเจอปัญหาใหญ่"],
["Buzz Lightyear","character","บัซ ไลท์เยียร์","Buzz says, \"To infinity and beyond.\" I want to go above and beyond in service.","บัซพูดว่า To infinity and beyond ฉันอยากบริการให้เกินความคาดหมาย"],
["SpongeBob","character","สพันจ์บ็อบ","SpongeBob loves his job and smiles every day. I want to work like that.","สพันจ์บ็อบรักงานและยิ้มทุกวัน ฉันอยากทำงานแบบนั้น"],
["Minions","character","มินเนียน","Minions are small, but together they show strong teamwork.","มินเนียนตัวเล็ก แต่รวมกันแล้วเป็นทีมเวิร์กที่แข็งแรง"],
["Shrek","character","เชร็ค","Shrek looks scary but is kind inside. We should not judge passengers by their look.","เชร็คดูน่ากลัวแต่ใจดี เราไม่ควรตัดสินผู้โดยสารจากภายนอก"],
["Rilakkuma","character","ริลัคคุมะ","Rilakkuma loves to relax. Rest is important, so we can work well again.","ริลัคคุมะชอบพักผ่อน การพักสำคัญ เพื่อให้กลับมาทำงานได้ดี"],
["Kumamon","character","คุมะมง","Kumamon makes his town famous. Crew also represent their airline and country.","คุมะมงทำให้เมืองของเขามีชื่อเสียง ลูกเรือก็เป็นตัวแทนสายการบินและประเทศ"],
["Labubu","character","ลาบูบู้","Labubu looks naughty but is cute and popular. Being different can be a strength.","ลาบูบู้ดูซนแต่น่ารักและคนชอบ ความแตกต่างเป็นจุดแข็งได้"],
["Sailor Moon","character","เซเลอร์มูน","Sailor Moon fights with her friends as a team. She is not strong alone.","เซเลอร์มูนสู้ไปกับเพื่อนเป็นทีม เธอไม่ได้เก่งคนเดียว"],
["Luffy","character","ลูฟี่","Luffy has a big dream and trusts his crew. A good crew goes far together.","ลูฟี่มีฝันที่ยิ่งใหญ่และเชื่อใจลูกเรือของเขา ทีมที่ดีไปได้ไกลด้วยกัน"],
["Conan","character","โคนัน","Conan notices small details and solves problems, like my work in R&D.","โคนันสังเกตรายละเอียดเล็ก ๆ และแก้ปัญหา เหมือนงาน R&D ของฉัน"],
["Totoro","character","โทโทโร่","Totoro is big, quiet and kind. He makes children feel safe.","โทโทโร่ตัวใหญ่ เงียบ และใจดี ทำให้เด็กรู้สึกปลอดภัย"],
["Stitch","character","สติทช์","Stitch says family means nobody gets left behind. Crew leave no passenger behind.","สติทช์บอกว่าครอบครัวคือไม่ทิ้งใครไว้ข้างหลัง ลูกเรือก็ไม่ทิ้งผู้โดยสารคนไหน"],
["Mr. Bean","character","มิสเตอร์บีน","Mr. Bean does not talk much, but everyone understands him. Body language is powerful.","มิสเตอร์บีนพูดน้อยแต่ทุกคนเข้าใจ ภาษากายมีพลังมาก"]
]]
);
