(window.VOCAB_GROUPS = window.VOCAB_GROUPS || []).push(
["safety", [
["safety","n.","ความปลอดภัย","Safety is our first priority.","ความปลอดภัยคือสิ่งสำคัญอันดับแรกของเรา"],
["security","n.","การรักษาความปลอดภัย","All bags go through a security check.","กระเป๋าทุกใบต้องผ่านการตรวจความปลอดภัย"],
["emergency","n.","เหตุฉุกเฉิน","Crew are trained to act fast in an emergency.","ลูกเรือถูกฝึกให้ลงมือเร็วในเหตุฉุกเฉิน"],
["evacuate","v.","อพยพ","We must evacuate the aircraft within 90 seconds.","เราต้องอพยพออกจากเครื่องบินภายใน 90 วินาที"],
["evacuation","n.","การอพยพ","Leave all bags behind during an evacuation.","ทิ้งสัมภาระทั้งหมดไว้ระหว่างการอพยพ"],
["procedure","n.","ขั้นตอนปฏิบัติ","I always follow the standard procedure.","ฉันทำตามขั้นตอนมาตรฐานเสมอ"],
["regulation","n.","กฎระเบียบ","Smoking is against aviation regulations.","การสูบบุหรี่ผิดกฎระเบียบการบิน"],
["comply","v.","ปฏิบัติตาม","All passengers must comply with crew instructions.","ผู้โดยสารทุกคนต้องปฏิบัติตามคำแนะนำของลูกเรือ"],
["demonstration","n.","การสาธิต","Please watch the safety demonstration carefully.","โปรดชมการสาธิตความปลอดภัยอย่างตั้งใจ"],
["seatbelt","n.","เข็มขัดนิรภัย","Please fasten your seatbelt.","โปรดรัดเข็มขัดนิรภัย"],
["fasten","v.","รัด คาด","Fasten your seatbelt low and tight.","รัดเข็มขัดให้ต่ำและกระชับ"],
["life jacket","n.","เสื้อชูชีพ","Your life jacket is under your seat.","เสื้อชูชีพอยู่ใต้ที่นั่งของคุณ"],
["oxygen mask","n.","หน้ากากออกซิเจน","Put on your own oxygen mask before helping others.","สวมหน้ากากออกซิเจนของตัวเองก่อนช่วยผู้อื่น"],
["emergency exit","n.","ทางออกฉุกเฉิน","The nearest emergency exit may be behind you.","ทางออกฉุกเฉินที่ใกล้ที่สุดอาจอยู่ด้านหลังคุณ"],
["exit row","n.","แถวที่นั่งติดทางออกฉุกเฉิน","Passengers in the exit row must be able to help.","ผู้โดยสารแถวทางออกฉุกเฉินต้องช่วยเหลือได้"],
["brace position","n.","ท่าเตรียมรับแรงกระแทก","Take the brace position when you hear the command.","เข้าท่าเตรียมรับแรงกระแทกเมื่อได้ยินคำสั่ง"],
["slide","n.","สไลด์หนีภัย","Jump onto the slide with your arms crossed.","กระโดดลงสไลด์โดยกอดอก"],
["life raft","n.","แพชูชีพ","The slide can be used as a life raft on water.","สไลด์ใช้เป็นแพชูชีพบนน้ำได้"],
["ditching","n.","การลงจอดฉุกเฉินบนน้ำ","Crew practise ditching in a pool during training.","ลูกเรือฝึกการลงจอดบนน้ำในสระระหว่างอบรม"],
["turbulence","n.","สภาพอากาศแปรปรวน หลุมอากาศ","We're expecting some turbulence ahead.","เราคาดว่าจะเจอสภาพอากาศแปรปรวนข้างหน้า"],
["decompression","n.","การสูญเสียความดันอากาศ","Oxygen masks drop during a decompression.","หน้ากากออกซิเจนจะหล่นลงเมื่อความดันอากาศลดลง"],
["fire extinguisher","n.","ถังดับเพลิง","I checked that the fire extinguisher was in place.","ฉันตรวจว่าถังดับเพลิงอยู่ประจำที่"],
["smoke detector","n.","เครื่องตรวจจับควัน","Each lavatory has a smoke detector.","ห้องน้ำทุกห้องมีเครื่องตรวจจับควัน"],
["hazard","n.","สิ่งอันตราย","A bag in the aisle is a safety hazard.","กระเป๋าที่วางบนทางเดินเป็นอันตรายต่อความปลอดภัย"],
["risk","n.","ความเสี่ยง","Crew are trained to reduce every risk.","ลูกเรือถูกฝึกให้ลดทุกความเสี่ยง"],
["prevent","v.","ป้องกัน","Checks before take-off help prevent accidents.","การตรวจก่อนเครื่องขึ้นช่วยป้องกันอุบัติเหตุ"],
["secure","v.","ยึดให้แน่น ทำให้ปลอดภัย","Please secure the galley before landing.","โปรดเก็บครัวให้เรียบร้อยก่อนลงจอด"],
["stow","v.","เก็บเข้าที่","Please stow your bag under the seat in front of you.","โปรดเก็บกระเป๋าไว้ใต้ที่นั่งด้านหน้า"],
["upright","adj.","ตั้งตรง","Return your seat to the upright position.","ปรับพนักเก้าอี้ให้ตั้งตรง"],
["switch off","phr. v.","ปิดเครื่อง","Please switch off your electronic devices.","โปรดปิดอุปกรณ์อิเล็กทรอนิกส์"],
["flight mode","n.","โหมดเครื่องบิน","Set your phone to flight mode.","ตั้งโทรศัพท์เป็นโหมดเครื่องบิน"],
["prohibited","adj.","ต้องห้าม","Smoking is prohibited throughout the flight.","ห้ามสูบบุหรี่ตลอดเที่ยวบิน"],
["dangerous goods","n.","วัตถุอันตราย","Power banks are dangerous goods in checked bags.","พาวเวอร์แบงก์ถือเป็นวัตถุอันตรายในกระเป๋าโหลด"],
["suspicious","adj.","น่าสงสัย","Report any suspicious item to the crew.","แจ้งลูกเรือหากพบสิ่งของน่าสงสัย"],
["unruly","adj.","ก่อความวุ่นวาย ไม่เชื่อฟัง","The captain was informed about the unruly passenger.","กัปตันได้รับแจ้งเรื่องผู้โดยสารที่ก่อความวุ่นวาย"],
["intoxicated","adj.","เมาสุรา","We don't serve alcohol to intoxicated passengers.","เราไม่เสิร์ฟแอลกอฮอล์ให้ผู้โดยสารที่เมา"],
["restrain","v.","ควบคุมตัว","Crew may restrain a violent passenger.","ลูกเรืออาจควบคุมตัวผู้โดยสารที่ใช้ความรุนแรง"],
["alert","adj.","ตื่นตัว","Crew must stay alert during take-off and landing.","ลูกเรือต้องตื่นตัวช่วงเครื่องขึ้นและลง"],
["aware","adj.","ตระหนักรู้","I'm always aware of what is happening around me.","ฉันรู้ตัวเสมอว่ารอบตัวเกิดอะไรขึ้น"],
["situational awareness","n.","การรับรู้สถานการณ์รอบตัว","Situational awareness helps crew spot problems early.","การรับรู้สถานการณ์ช่วยให้ลูกเรือเห็นปัญหาได้เร็ว"],
["precaution","n.","มาตรการป้องกันล่วงหน้า","As a precaution, please remain seated.","เพื่อความปลอดภัย โปรดนั่งอยู่กับที่"],
["command","n.","คำสั่ง","Follow the crew's commands in an emergency.","ทำตามคำสั่งของลูกเรือในเหตุฉุกเฉิน"],
["assess","v.","ประเมิน","First I assess the situation.","อันดับแรกฉันประเมินสถานการณ์"],
["remain seated","phr.","นั่งอยู่กับที่","Please remain seated until the seatbelt sign is off.","โปรดนั่งอยู่กับที่จนกว่าสัญญาณรัดเข็มขัดจะดับ"],
["leave behind","phr. v.","ทิ้งไว้","Leave everything behind and go to the exit.","ทิ้งทุกอย่างไว้แล้วไปที่ทางออก"],
["inflate","v.","เป่าลมให้พอง","Inflate your life jacket only outside the aircraft.","ทำให้เสื้อชูชีพพองเมื่ออยู่นอกเครื่องบินเท่านั้น"],
["floor lighting","n.","ไฟนำทางที่พื้น","Floor lighting will guide you to the exits.","ไฟที่พื้นจะนำทางคุณไปยังทางออก"],
["safety card","n.","บัตรแนะนำความปลอดภัย","The safety card is in your seat pocket.","บัตรแนะนำความปลอดภัยอยู่ในกระเป๋าหน้าที่นั่ง"],
["cabin secure","phr.","ห้องโดยสารพร้อมและปลอดภัย","I reported 'cabin secure' to the purser.","ฉันรายงานหัวหน้าว่าห้องโดยสารพร้อม"],
["arm","v.","เตรียมประตูให้สไลด์พร้อมใช้","Cabin crew, arm doors and cross-check.","ลูกเรือ เตรียมประตูและตรวจสอบไขว้"],
["disarm","v.","ปลดระบบสไลด์ที่ประตู","Disarm the doors after the aircraft has stopped.","ปลดระบบประตูหลังเครื่องจอดสนิท"],
["cross-check","v.","ตรวจสอบไขว้ซึ่งกันและกัน","We cross-check each other's doors.","เราตรวจสอบประตูของกันและกัน"],
["standard operating procedure","n.","ขั้นตอนปฏิบัติมาตรฐาน (SOP)","Crew follow the standard operating procedure for every task.","ลูกเรือทำตาม SOP ในทุกงาน"],
["drill","n.","การซ้อมปฏิบัติ","We practise evacuation drills every year.","เราซ้อมอพยพทุกปี"],
["incident","n.","เหตุการณ์ไม่ปกติ","Every incident must be written in the report.","ทุกเหตุการณ์ต้องบันทึกลงในรายงาน"],
["injury","n.","การบาดเจ็บ","Turbulence can cause serious injuries.","หลุมอากาศอาจทำให้บาดเจ็บรุนแรงได้"],
["panic","v.","ตื่นตระหนก","Passengers won't panic if the crew stay calm.","ผู้โดยสารจะไม่ตื่นตระหนกหากลูกเรือสงบ"],
["protect","v.","ปกป้อง","Our job is to protect everyone onboard.","งานของเราคือปกป้องทุกคนบนเครื่อง"],
["monitor","v.","เฝ้าสังเกต","We monitor the cabin every twenty minutes.","เราเดินตรวจห้องโดยสารทุกยี่สิบนาที"],
["vigilant","adj.","ระแวดระวัง","Stay vigilant, especially during boarding.","ระแวดระวังอยู่เสมอ โดยเฉพาะช่วงขึ้นเครื่อง"]
]],
["cabin", [
["aircraft","n.","เครื่องบิน อากาศยาน","The aircraft is a Boeing 777.","เครื่องบินลำนี้คือโบอิ้ง 777"],
["cabin","n.","ห้องโดยสาร","The cabin lights will be dimmed for take-off.","ไฟในห้องโดยสารจะหรี่ลงสำหรับการขึ้นบิน"],
["cabin crew","n.","ลูกเรือ","Cabin crew are onboard mainly for your safety.","ลูกเรืออยู่บนเครื่องเพื่อความปลอดภัยของคุณเป็นหลัก"],
["flight attendant","n.","พนักงานต้อนรับบนเครื่องบิน","She has been a flight attendant for ten years.","เธอเป็นพนักงานต้อนรับบนเครื่องบินมาสิบปี"],
["purser","n.","หัวหน้าลูกเรือ","The purser leads the cabin crew team.","หัวหน้าลูกเรือเป็นผู้นำทีมลูกเรือ"],
["captain","n.","กัปตัน","The captain makes the final decision.","กัปตันเป็นผู้ตัดสินใจขั้นสุดท้าย"],
["first officer","n.","นักบินผู้ช่วย","The first officer sits on the right side.","นักบินผู้ช่วยนั่งด้านขวา"],
["flight deck","n.","ห้องนักบิน","Only authorised crew may enter the flight deck.","เฉพาะลูกเรือที่ได้รับอนุญาตเข้าห้องนักบินได้"],
["cockpit","n.","ห้องนักบิน","The cockpit door stays locked during the flight.","ประตูห้องนักบินล็อกตลอดเที่ยวบิน"],
["galley","n.","ครัวบนเครื่องบิน","We prepare meals in the galley.","เราเตรียมอาหารในครัวบนเครื่อง"],
["lavatory","n.","ห้องน้ำบนเครื่องบิน","The lavatory is at the rear of the cabin.","ห้องน้ำอยู่ท้ายห้องโดยสาร"],
["aisle","n.","ทางเดิน","Please keep the aisle clear.","โปรดอย่าวางของขวางทางเดิน"],
["aisle seat","n.","ที่นั่งริมทางเดิน","Would you prefer an aisle seat?","คุณต้องการที่นั่งริมทางเดินไหมคะ"],
["window seat","n.","ที่นั่งริมหน้าต่าง","She asked for a window seat.","เธอขอที่นั่งริมหน้าต่าง"],
["middle seat","n.","ที่นั่งตรงกลาง","He was unhappy with his middle seat.","เขาไม่พอใจที่ได้ที่นั่งตรงกลาง"],
["row","n.","แถว","Your seat is in row 23.","ที่นั่งของคุณอยู่แถว 23"],
["overhead locker","n.","ช่องเก็บสัมภาระเหนือศีรษะ","Place heavy bags carefully in the overhead locker.","วางกระเป๋าหนักในช่องเหนือศีรษะอย่างระมัดระวัง"],
["overhead bin","n.","ช่องเก็บของเหนือศีรษะ","The overhead bins are full.","ช่องเก็บของเหนือศีรษะเต็มแล้ว"],
["seat pocket","n.","กระเป๋าหลังที่นั่ง","The menu is in your seat pocket.","เมนูอยู่ในกระเป๋าหลังที่นั่ง"],
["tray table","n.","ถาดพับหน้าที่นั่ง","Please fold away your tray table.","โปรดพับเก็บถาดหน้าที่นั่ง"],
["armrest","n.","ที่วางแขน","The remote control is in your armrest.","รีโมตอยู่ในที่วางแขน"],
["headrest","n.","ที่พิงศีรษะ","You can adjust the headrest for comfort.","คุณปรับที่พิงศีรษะให้สบายได้"],
["recline","v.","ปรับเอนเก้าอี้","Press the button to recline your seat.","กดปุ่มเพื่อปรับเอนที่นั่ง"],
["window shade","n.","ม่านหน้าต่าง","Please open your window shade for landing.","โปรดเปิดม่านหน้าต่างสำหรับการลงจอด"],
["call button","n.","ปุ่มเรียกลูกเรือ","Press the call button if you need anything.","กดปุ่มเรียกหากต้องการอะไร"],
["reading light","n.","ไฟอ่านหนังสือ","Your reading light is above your seat.","ไฟอ่านหนังสืออยู่เหนือที่นั่ง"],
["jump seat","n.","ที่นั่งลูกเรือ","Crew sit on the jump seat for take-off.","ลูกเรือนั่งที่นั่งลูกเรือช่วงเครื่องขึ้น"],
["bulkhead","n.","ผนังกั้นห้องโดยสาร","Bulkhead seats have more legroom.","ที่นั่งหลังผนังกั้นมีที่วางขามากกว่า"],
["bassinet","n.","เปลเด็กทารกบนเครื่อง","We can fit a bassinet for your baby after take-off.","เราติดตั้งเปลให้ลูกน้อยของคุณได้หลังเครื่องขึ้น"],
["legroom","n.","พื้นที่วางขา","Exit row seats offer extra legroom.","ที่นั่งแถวทางออกมีที่วางขาเพิ่ม"],
["economy class","n.","ชั้นประหยัด","New crew usually start in economy class.","ลูกเรือใหม่มักเริ่มที่ชั้นประหยัด"],
["business class","n.","ชั้นธุรกิจ","Business class passengers board first.","ผู้โดยสารชั้นธุรกิจขึ้นเครื่องก่อน"],
["first class","n.","ชั้นหนึ่ง","First class offers private suites.","ชั้นหนึ่งมีห้องสวีทส่วนตัว"],
["trolley","n.","รถเข็นบริการ","Mind your elbows, the trolley is coming through.","ระวังข้อศอกนะคะ รถเข็นกำลังผ่าน"],
["cart","n.","รถเข็น (อเมริกัน)","Lock the cart when you stop in the aisle.","ล็อกรถเข็นเมื่อหยุดบนทางเดิน"],
["blanket","n.","ผ้าห่ม","Would you like a blanket?","รับผ้าห่มไหมคะ"],
["pillow","n.","หมอน","I'll bring you an extra pillow.","เดี๋ยวฉันนำหมอนมาเพิ่มให้"],
["headset","n.","หูฟัง","Headsets are in the seat pocket.","หูฟังอยู่ในกระเป๋าหลังที่นั่ง"],
["amenity kit","n.","ชุดของใช้บนเครื่อง","Each passenger receives an amenity kit.","ผู้โดยสารทุกคนได้รับชุดของใช้"],
["in-flight entertainment","n.","ความบันเทิงบนเครื่อง","Our in-flight entertainment has over 500 films.","ระบบความบันเทิงของเรามีภาพยนตร์กว่า 500 เรื่อง"],
["announcement","n.","ประกาศ","The purser made an announcement about the delay.","หัวหน้าลูกเรือประกาศเรื่องความล่าช้า"],
["public address","n.","ระบบประกาศ (PA)","I practised reading the public address in two languages.","ฉันฝึกอ่านประกาศสองภาษา"],
["interphone","n.","โทรศัพท์ภายในเครื่อง","I called the purser on the interphone.","ฉันโทรหาหัวหน้าลูกเรือทางโทรศัพท์ภายใน"],
["seatbelt sign","n.","สัญญาณรัดเข็มขัด","The captain has switched on the seatbelt sign.","กัปตันเปิดสัญญาณรัดเข็มขัดแล้ว"],
["cabin pressure","n.","ความดันในห้องโดยสาร","Your ears may hurt as the cabin pressure changes.","หูอาจอื้อเมื่อความดันในห้องโดยสารเปลี่ยน"],
["wing","n.","ปีกเครื่องบิน","There are emergency exits over the wings.","มีทางออกฉุกเฉินเหนือปีก"],
["engine","n.","เครื่องยนต์","This aircraft has two engines.","เครื่องบินลำนี้มีสองเครื่องยนต์"],
["fuselage","n.","ลำตัวเครื่องบิน","The airline's logo is painted on the fuselage.","โลโก้สายการบินอยู่บนลำตัวเครื่อง"],
["cargo hold","n.","ห้องเก็บสัมภาระใต้ท้องเครื่อง","Large bags travel in the cargo hold.","กระเป๋าใบใหญ่อยู่ในห้องสัมภาระใต้ท้องเครื่อง"],
["forward","adj.","ด้านหน้า","Please use the forward lavatory.","โปรดใช้ห้องน้ำด้านหน้า"],
["aft","adj.","ด้านท้าย","The aft galley is at the back of the aircraft.","ครัวท้ายอยู่ด้านหลังเครื่องบิน"],
["wide-body","adj.","ลำตัวกว้าง (สองทางเดิน)","The A380 is a wide-body aircraft.","A380 เป็นเครื่องบินลำตัวกว้าง"],
["narrow-body","adj.","ลำตัวแคบ (ทางเดินเดียว)","The A320 is a narrow-body aircraft.","A320 เป็นเครื่องบินลำตัวแคบ"],
["fleet","n.","ฝูงบิน","Your airline has one of the youngest fleets.","สายการบินของคุณมีฝูงบินที่ใหม่ที่สุดแห่งหนึ่ง"],
["onboard","adv.","บนเครื่อง","Welcome onboard.","ยินดีต้อนรับขึ้นเครื่อง"],
["crew rest","n.","ที่พักลูกเรือ","Crew take turns sleeping in the crew rest area.","ลูกเรือผลัดกันนอนในที่พักลูกเรือ"],
["door","n.","ประตูเครื่องบิน","I was responsible for door 2 left.","ฉันรับผิดชอบประตู 2 ซ้าย"],
["dim","v.","หรี่ไฟ","We dim the cabin lights at night.","เราหรี่ไฟห้องโดยสารตอนกลางคืน"],
["ventilation","n.","การระบายอากาศ","You can adjust the ventilation above your seat.","คุณปรับช่องลมเหนือที่นั่งได้"],
["emergency equipment","n.","อุปกรณ์ฉุกเฉิน","We check all emergency equipment before boarding.","เราตรวจอุปกรณ์ฉุกเฉินทั้งหมดก่อนผู้โดยสารขึ้นเครื่อง"]
]],
["ops", [
["airline","n.","สายการบิน","I've wanted to join this airline for years.","ฉันอยากร่วมงานกับสายการบินนี้มาหลายปี"],
["flight","n.","เที่ยวบิน","The flight to London takes twelve hours.","เที่ยวบินไปลอนดอนใช้เวลาสิบสองชั่วโมง"],
["destination","n.","จุดหมายปลายทาง","You fly to more than 150 destinations.","คุณบินไปกว่า 150 จุดหมาย"],
["route","n.","เส้นทางบิน","The airline opened a new route to Osaka.","สายการบินเปิดเส้นทางใหม่ไปโอซากา"],
["hub","n.","ศูนย์กลางการบิน","Dubai is the airline's hub.","ดูไบเป็นศูนย์กลางการบินของสายการบิน"],
["base","n.","ฐานประจำการ","I'm happy to be based in Bangkok or abroad.","ฉันยินดีประจำที่กรุงเทพฯ หรือต่างประเทศ"],
["domestic","adj.","ภายในประเทศ","Domestic flights are usually under two hours.","เที่ยวบินในประเทศมักไม่เกินสองชั่วโมง"],
["international","adj.","ระหว่างประเทศ","I enjoy working with international passengers.","ฉันชอบทำงานกับผู้โดยสารต่างชาติ"],
["long-haul","adj.","ระยะไกล","Long-haul flights need good stamina.","เที่ยวบินระยะไกลต้องใช้ความอึด"],
["short-haul","adj.","ระยะใกล้","Short-haul service must be very fast.","บริการในเที่ยวบินระยะใกล้ต้องเร็วมาก"],
["layover","n.","การพักค้างที่เมืองปลายทาง","We have a 24-hour layover in Paris.","เรามีพักค้าง 24 ชั่วโมงที่ปารีส"],
["turnaround","n.","เที่ยวบินไปกลับไม่ค้างคืน","Today I'm on a turnaround to Singapore.","วันนี้ฉันบินไปกลับสิงคโปร์แบบไม่ค้างคืน"],
["roster","n.","ตารางบิน","My roster changes every month.","ตารางบินของฉันเปลี่ยนทุกเดือน"],
["standby","n.","เวรสำรอง","I'm on standby this weekend.","สุดสัปดาห์นี้ฉันอยู่เวรสำรอง"],
["jet lag","n.","อาการเมาเวลา","I manage jet lag by drinking water and sleeping well.","ฉันรับมือกับเจ็ตแล็กด้วยการดื่มน้ำและนอนให้พอ"],
["time zone","n.","เขตเวลา","Crew cross several time zones in one flight.","ลูกเรือข้ามหลายเขตเวลาในเที่ยวบินเดียว"],
["take-off","n.","การขึ้นบิน","Please remain seated during take-off.","โปรดนั่งอยู่กับที่ระหว่างเครื่องขึ้น"],
["landing","n.","การลงจอด","We will begin our descent for landing shortly.","เราจะเริ่มลดระดับเพื่อลงจอดในไม่ช้า"],
["taxi","v.","เคลื่อนตัวบนทางขับ","The aircraft is taxiing to the runway.","เครื่องบินกำลังเคลื่อนไปยังทางวิ่ง"],
["cruise","n.","ช่วงบินระดับ","Meal service starts during cruise.","การบริการอาหารเริ่มในช่วงบินระดับ"],
["descent","n.","การลดระดับ","We have started our descent into Bangkok.","เราเริ่มลดระดับสู่กรุงเทพฯ แล้ว"],
["altitude","n.","ระดับความสูง","We are flying at an altitude of 38,000 feet.","เรากำลังบินที่ระดับความสูง 38,000 ฟุต"],
["runway","n.","ทางวิ่ง","We're waiting for a free runway.","เรากำลังรอทางวิ่งว่าง"],
["gate","n.","ประตูขึ้นเครื่อง","Boarding is at gate C12.","ขึ้นเครื่องที่ประตู C12"],
["terminal","n.","อาคารผู้โดยสาร","International flights leave from Terminal 2.","เที่ยวบินระหว่างประเทศออกจากอาคาร 2"],
["boarding","n.","การขึ้นเครื่อง","Boarding will begin in ten minutes.","จะเริ่มขึ้นเครื่องในอีกสิบนาที"],
["boarding pass","n.","บัตรขึ้นเครื่อง","May I see your boarding pass, please?","ขอดูบัตรขึ้นเครื่องด้วยค่ะ"],
["disembark","v.","ลงจากเครื่อง","Please take all your belongings when you disembark.","โปรดนำสัมภาระทั้งหมดไปด้วยเมื่อลงจากเครื่อง"],
["check-in","n.","การเช็กอิน","Check-in closes one hour before departure.","เช็กอินปิดก่อนเครื่องออกหนึ่งชั่วโมง"],
["departure","n.","การออกเดินทาง","Our departure is delayed by thirty minutes.","เวลาออกเดินทางล่าช้าสามสิบนาที"],
["arrival","n.","การมาถึง","Our estimated arrival time is 6 p.m.","เวลาถึงโดยประมาณคือ 18.00 น."],
["delay","n.","ความล่าช้า","We apologise for the delay.","ขออภัยในความล่าช้า"],
["cancel","v.","ยกเลิก","The flight was cancelled because of the storm.","เที่ยวบินถูกยกเลิกเพราะพายุ"],
["divert","v.","เปลี่ยนเส้นทางไปลงสนามบินอื่น","We diverted to Phuket for a medical emergency.","เราเปลี่ยนไปลงภูเก็ตเพราะเหตุฉุกเฉินทางการแพทย์"],
["connecting flight","n.","เที่ยวบินต่อ","Ground staff will help with your connecting flight.","พนักงานภาคพื้นจะช่วยเรื่องเที่ยวบินต่อของคุณ"],
["transit","n.","การแวะเปลี่ยนเครื่อง","Passengers in transit should stay in the terminal.","ผู้โดยสารเปลี่ยนเครื่องควรอยู่ในอาคาร"],
["baggage","n.","สัมภาระ","Please collect your baggage at belt 5.","โปรดรับสัมภาระที่สายพาน 5"],
["carry-on","n.","กระเป๋าถือขึ้นเครื่อง","Each passenger may bring one carry-on.","ผู้โดยสารแต่ละคนนำกระเป๋าขึ้นเครื่องได้หนึ่งใบ"],
["checked baggage","n.","สัมภาระโหลดใต้เครื่อง","Liquids over 100 ml go in checked baggage.","ของเหลวเกิน 100 มล. ต้องอยู่ในสัมภาระโหลด"],
["baggage allowance","n.","น้ำหนักสัมภาระที่อนุญาต","Your baggage allowance is 30 kilograms.","น้ำหนักสัมภาระที่อนุญาตคือ 30 กิโลกรัม"],
["customs","n.","ศุลกากร","You'll go through customs after baggage claim.","คุณจะผ่านศุลกากรหลังรับกระเป๋า"],
["immigration","n.","ตรวจคนเข้าเมือง","Please fill in the immigration form before landing.","โปรดกรอกแบบฟอร์มตรวจคนเข้าเมืองก่อนลงจอด"],
["ground staff","n.","พนักงานภาคพื้น","Ground staff will meet you at the gate.","พนักงานภาคพื้นจะรอคุณที่ประตู"],
["flight number","n.","หมายเลขเที่ยวบิน","Your flight number is TG 910.","หมายเลขเที่ยวบินของคุณคือ TG 910"],
["local time","n.","เวลาท้องถิ่น","The local time in Tokyo is 8 a.m.","เวลาท้องถิ่นในโตเกียวคือ 8 โมงเช้า"],
["weather conditions","n.","สภาพอากาศ","We're delayed due to weather conditions.","เราล่าช้าเนื่องจากสภาพอากาศ"],
["on behalf of","phr.","ในนามของ","On behalf of the crew, thank you for flying with us.","ในนามของลูกเรือ ขอบคุณที่บินกับเรา"],
["full-service","adj.","บริการเต็มรูปแบบ","Thai Airways is a full-service airline.","การบินไทยเป็นสายการบินบริการเต็มรูปแบบ"],
["low-cost","adj.","ต้นทุนต่ำ","Low-cost airlines sell food and drinks onboard.","สายการบินต้นทุนต่ำขายอาหารและเครื่องดื่มบนเครื่อง"],
["codeshare","n.","เที่ยวบินร่วมรหัส","This is a codeshare flight with our partner airline.","นี่คือเที่ยวบินร่วมรหัสกับสายการบินพันธมิตร"]
]],
["meal", [
["meal service","n.","การบริการอาหาร","Meal service begins after take-off.","การบริการอาหารเริ่มหลังเครื่องขึ้น"],
["beverage","n.","เครื่องดื่ม","Would you like a hot or cold beverage?","รับเครื่องดื่มร้อนหรือเย็นดีคะ"],
["refreshment","n.","ของว่างและเครื่องดื่ม","Light refreshments will be served shortly.","จะมีบริการของว่างในอีกสักครู่"],
["snack","n.","ของว่าง","We offer a snack before landing.","เรามีของว่างให้ก่อนลงจอด"],
["special meal","n.","อาหารพิเศษ","Special meals are delivered before the main service.","อาหารพิเศษจะเสิร์ฟก่อนบริการหลัก"],
["vegetarian","adj.","มังสวิรัติ","We have a vegetarian option today.","วันนี้เรามีเมนูมังสวิรัติ"],
["vegan","adj.","วีแกน ไม่ทานผลิตภัณฑ์จากสัตว์","She ordered a vegan meal in advance.","เธอสั่งอาหารวีแกนล่วงหน้า"],
["halal","adj.","ฮาลาล","All meals on this flight are halal.","อาหารทุกชุดในเที่ยวบินนี้เป็นฮาลาล"],
["kosher","adj.","โคเชอร์ (ตามหลักศาสนายิว)","Kosher meals must be ordered 48 hours ahead.","อาหารโคเชอร์ต้องสั่งล่วงหน้า 48 ชั่วโมง"],
["gluten-free","adj.","ปราศจากกลูเตน","Do you have a gluten-free meal?","มีอาหารปราศจากกลูเตนไหม"],
["dietary requirement","n.","ข้อจำกัดด้านอาหาร","Do you have any dietary requirements?","คุณมีข้อจำกัดด้านอาหารไหมคะ"],
["allergy","n.","อาการแพ้","Do you have any food allergies?","คุณแพ้อาหารอะไรไหมคะ"],
["ingredient","n.","ส่วนผสม","Let me check the ingredients for you.","ขอตรวจสอบส่วนผสมให้นะคะ"],
["contain","v.","มีส่วนผสมของ","This dessert contains nuts.","ของหวานนี้มีถั่ว"],
["main course","n.","อาหารจานหลัก","For the main course, we have chicken or fish.","จานหลักมีไก่หรือปลา"],
["dessert","n.","ของหวาน","Would you like dessert with your coffee?","รับของหวานคู่กับกาแฟไหมคะ"],
["appetiser","n.","อาหารเรียกน้ำย่อย","The appetiser is a smoked salmon salad.","อาหารเรียกน้ำย่อยคือสลัดแซลมอนรมควัน"],
["sparkling water","n.","น้ำโซดา น้ำมีฟอง","Would you like still or sparkling water?","รับน้ำเปล่าหรือน้ำมีฟองคะ"],
["still water","n.","น้ำเปล่า","A glass of still water, please.","ขอน้ำเปล่าหนึ่งแก้ว"],
["soft drink","n.","น้ำอัดลม","We have a selection of soft drinks and juices.","เรามีน้ำอัดลมและน้ำผลไม้ให้เลือก"],
["alcohol","n.","เครื่องดื่มแอลกอฮอล์","We serve alcohol responsibly.","เราเสิร์ฟแอลกอฮอล์อย่างมีความรับผิดชอบ"],
["spirits","n.","เหล้า สุรากลั่น","Spirits are served with ice or a mixer.","สุราเสิร์ฟพร้อมน้ำแข็งหรือมิกเซอร์"],
["decaf","adj.","ไม่มีคาเฟอีน","Would you prefer regular or decaf coffee?","รับกาแฟธรรมดาหรือไม่มีคาเฟอีนคะ"],
["complimentary","adj.","ให้บริการฟรี","All drinks are complimentary on this flight.","เครื่องดื่มทุกชนิดฟรีในเที่ยวบินนี้"],
["duty-free","adj.","ปลอดภาษี","Duty-free sales will begin after the meal.","การขายสินค้าปลอดภาษีจะเริ่มหลังอาหาร"],
["cutlery","n.","ช้อนส้อมมีด","Your cutlery is inside the napkin.","ช้อนส้อมอยู่ในผ้าเช็ดปาก"],
["napkin","n.","ผ้าหรือกระดาษเช็ดปาก","Could I have another napkin?","ขอกระดาษเช็ดปากเพิ่มได้ไหม"],
["tray","n.","ถาดอาหาร","May I clear your tray?","ขออนุญาตเก็บถาดนะคะ"],
["refill","n.","การเติม","Would you like a refill?","รับเพิ่มไหมคะ"],
["pour","v.","ริน เท","I pour hot drinks away from the passenger.","ฉันรินเครื่องดื่มร้อนให้ห่างจากตัวผู้โดยสาร"],
["spill","v.","ทำหก","I'm so sorry, I spilled some water.","ขอโทษมากค่ะ ฉันทำน้ำหก"],
["clear","v.","เก็บ (ถาด จาน)","We clear the trays before landing.","เราเก็บถาดก่อนลงจอด"],
["heat","v.","อุ่นอาหาร","We heat the meals in the galley ovens.","เราอุ่นอาหารในเตาอบของครัว"],
["portion","n.","ปริมาณต่อหนึ่งที่","Each portion is prepared before the flight.","อาหารแต่ละที่เตรียมไว้ก่อนบิน"],
["run out of","phr. v.","หมด","I'm afraid we have run out of chicken.","เกรงว่าไก่จะหมดแล้วค่ะ"],
["choice","n.","ตัวเลือก","Today's choices are beef curry or pasta.","ตัวเลือกวันนี้คือแกงเนื้อหรือพาสต้า"],
["pre-order","v.","สั่งล่วงหน้า","You can pre-order meals on our website.","คุณสั่งอาหารล่วงหน้าได้บนเว็บไซต์"],
["catering","n.","ฝ่ายจัดเตรียมอาหาร","Catering loads the meals before departure.","ฝ่ายครัวนำอาหารขึ้นเครื่องก่อนออกเดินทาง"],
["hygiene","n.","สุขอนามัย","Food hygiene is very important in the galley.","สุขอนามัยอาหารสำคัญมากในครัว"],
["baby food","n.","อาหารเด็กอ่อน","We can warm baby food for you.","เราอุ่นอาหารเด็กให้คุณได้"]
]],
["medical", [
["first aid","n.","การปฐมพยาบาล","All crew are trained in first aid.","ลูกเรือทุกคนผ่านการอบรมปฐมพยาบาล"],
["first aid kit","n.","ชุดปฐมพยาบาล","The first aid kit is stored near the galley.","ชุดปฐมพยาบาลเก็บอยู่ใกล้ครัว"],
["CPR","n.","การปั๊มหัวใจช่วยชีวิต","I learned CPR on a first aid course.","ฉันเรียนการปั๊มหัวใจจากคอร์สปฐมพยาบาล"],
["defibrillator","n.","เครื่องกระตุกหัวใจ (AED)","There is a defibrillator onboard.","มีเครื่องกระตุกหัวใจบนเครื่อง"],
["unconscious","adj.","หมดสติ","The passenger was unconscious but breathing.","ผู้โดยสารหมดสติแต่ยังหายใจ"],
["faint","v.","เป็นลม","A passenger fainted near the lavatory.","ผู้โดยสารเป็นลมใกล้ห้องน้ำ"],
["dizzy","adj.","เวียนหัว","She felt dizzy after standing up.","เธอเวียนหัวหลังลุกขึ้นยืน"],
["nausea","n.","อาการคลื่นไส้","Ginger tea can help with nausea.","ชาขิงช่วยบรรเทาอาการคลื่นไส้ได้"],
["airsick","adj.","เมาเครื่องบิน","There is a bag in the seat pocket if you feel airsick.","มีถุงในกระเป๋าหลังที่นั่งหากคุณเมาเครื่อง"],
["vomit","v.","อาเจียน","The child vomited during the descent.","เด็กอาเจียนช่วงลดระดับ"],
["headache","n.","ปวดหัว","He asked for water because of a headache.","เขาขอน้ำเพราะปวดหัว"],
["fever","n.","ไข้","The baby seems to have a fever.","เด็กทารกดูเหมือนมีไข้"],
["chest pain","n.","เจ็บหน้าอก","Chest pain is treated as a medical emergency.","อาการเจ็บหน้าอกถือเป็นเหตุฉุกเฉินทางการแพทย์"],
["shortness of breath","n.","หายใจลำบาก","We gave oxygen for his shortness of breath.","เราให้ออกซิเจนเพราะเขาหายใจลำบาก"],
["allergic reaction","n.","อาการแพ้","She had an allergic reaction to peanuts.","เธอมีอาการแพ้ถั่วลิสง"],
["asthma","n.","โรคหอบหืด","He has asthma and carries an inhaler.","เขาเป็นหอบหืดและพกยาพ่น"],
["diabetes","n.","โรคเบาหวาน","A passenger with diabetes needed something sweet.","ผู้โดยสารที่เป็นเบาหวานต้องการของหวาน"],
["seizure","n.","อาการชัก","Clear the area if someone has a seizure.","เคลียร์พื้นที่หากมีคนชัก"],
["heart attack","n.","หัวใจวาย","Crew are trained to recognise a heart attack.","ลูกเรือถูกฝึกให้สังเกตอาการหัวใจวาย"],
["choke","v.","สำลัก ติดคอ","A child was choking on a sweet.","เด็กสำลักลูกอม"],
["bleed","v.","เลือดออก","Press firmly if the wound is bleeding.","กดให้แน่นหากแผลมีเลือดออก"],
["burn","n.","แผลไหม้ แผลน้ำร้อนลวก","Cool a burn with water for ten minutes.","ราดน้ำเย็นที่แผลไหม้สิบนาที"],
["medication","n.","ยา","Keep your medication in your carry-on.","เก็บยาไว้ในกระเป๋าถือขึ้นเครื่อง"],
["symptom","n.","อาการ","What symptoms are you experiencing?","คุณมีอาการอย่างไรบ้างคะ"],
["pregnant","adj.","ตั้งครรภ์","Pregnant passengers may need a medical certificate.","ผู้โดยสารตั้งครรภ์อาจต้องมีใบรับรองแพทย์"],
["wheelchair","n.","รถเข็นผู้โดยสาร","A wheelchair will be waiting at the door.","จะมีรถเข็นรออยู่ที่ประตู"],
["unaccompanied minor","n.","เด็กเดินทางคนเดียว","I looked after an unaccompanied minor on the flight.","ฉันดูแลเด็กที่เดินทางคนเดียวในเที่ยวบิน"],
["elderly","adj.","สูงอายุ","We offer extra help to elderly passengers.","เราช่วยเหลือผู้โดยสารสูงอายุเป็นพิเศษ"],
["mobility","n.","การเคลื่อนไหวร่างกาย","Passengers with reduced mobility board first.","ผู้โดยสารที่เคลื่อนไหวลำบากขึ้นเครื่องก่อน"],
["dehydrated","adj.","ขาดน้ำ","Drink water so you don't get dehydrated.","ดื่มน้ำเพื่อไม่ให้ร่างกายขาดน้ำ"]
]]
);
