// Row: [word, part of speech, Thai meaning, example, Thai translation of example]
(window.VOCAB_GROUPS = window.VOCAB_GROUPS || []).push(
["quality", [
["adaptable","adj.","ปรับตัวเก่ง","I'm adaptable and settle into new teams quickly.","ฉันปรับตัวเก่งและเข้ากับทีมใหม่ได้เร็ว"],
["approachable","adj.","เข้าถึงง่าย เป็นกันเอง","Passengers find me approachable because I smile a lot.","ผู้โดยสารรู้สึกว่าฉันเข้าถึงง่ายเพราะฉันยิ้มบ่อย"],
["attentive","adj.","เอาใจใส่ ช่างสังเกต","A good crew member is attentive to small details.","ลูกเรือที่ดีใส่ใจในรายละเอียดเล็ก ๆ"],
["calm","adj.","ใจเย็น สงบ","I stay calm when customers are upset.","ฉันใจเย็นเมื่อลูกค้าไม่พอใจ"],
["caring","adj.","ห่วงใย ใส่ใจผู้อื่น","I'm a caring person who enjoys helping others.","ฉันเป็นคนใส่ใจและชอบช่วยเหลือผู้อื่น"],
["cheerful","adj.","ร่าเริง แจ่มใส","My colleagues say I'm cheerful even on long shifts.","เพื่อนร่วมงานบอกว่าฉันร่าเริงแม้ในกะยาว"],
["committed","adj.","ทุ่มเท มุ่งมั่น","I'm fully committed to a long-term career in aviation.","ฉันมุ่งมั่นกับอาชีพระยะยาวในวงการบิน"],
["compassionate","adj.","มีความเห็นอกเห็นใจ","She was compassionate towards the nervous passenger.","เธอเห็นอกเห็นใจผู้โดยสารที่กังวล"],
["confident","adj.","มั่นใจ","I'm confident speaking in front of a group.","ฉันมั่นใจในการพูดต่อหน้าคนกลุ่มใหญ่"],
["considerate","adj.","เกรงใจ คำนึงถึงผู้อื่น","Be considerate of passengers who are sleeping.","ควรเกรงใจผู้โดยสารที่กำลังนอนหลับ"],
["cooperative","adj.","ให้ความร่วมมือ","I'm cooperative and easy to work with.","ฉันให้ความร่วมมือและทำงานด้วยง่าย"],
["courteous","adj.","สุภาพ มีมารยาท","Crew must be courteous at all times.","ลูกเรือต้องสุภาพตลอดเวลา"],
["dedicated","adj.","อุทิศตน ตั้งใจจริง","I'm dedicated to giving the best service I can.","ฉันตั้งใจให้บริการที่ดีที่สุดเท่าที่ทำได้"],
["dependable","adj.","พึ่งพาได้","My manager describes me as dependable.","ผู้จัดการบอกว่าฉันเป็นคนที่พึ่งพาได้"],
["detail-oriented","adj.","ใส่ใจรายละเอียด","I'm detail-oriented when I check equipment.","ฉันใส่ใจรายละเอียดเวลาตรวจอุปกรณ์"],
["diligent","adj.","ขยันหมั่นเพียร","I was a diligent student and never missed a class.","ฉันเป็นนักเรียนที่ขยันและไม่เคยขาดเรียน"],
["diplomatic","adj.","มีวาทศิลป์ รู้จักพูดถนอมน้ำใจ","I gave a diplomatic answer to avoid conflict.","ฉันตอบอย่างถนอมน้ำใจเพื่อเลี่ยงความขัดแย้ง"],
["disciplined","adj.","มีระเบียบวินัย","Shift work has made me very disciplined.","การทำงานเป็นกะทำให้ฉันมีวินัยมาก"],
["easy-going","adj.","สบาย ๆ เข้ากับคนง่าย","I'm easy-going and get along with everyone.","ฉันเป็นคนสบาย ๆ และเข้ากับทุกคนได้"],
["efficient","adj.","มีประสิทธิภาพ","We need to be efficient during a short flight.","เราต้องทำงานอย่างมีประสิทธิภาพในเที่ยวบินระยะสั้น"],
["empathetic","adj.","เข้าใจความรู้สึกผู้อื่น","Being empathetic helps me calm angry customers.","การเข้าใจความรู้สึกผู้อื่นช่วยให้ฉันทำให้ลูกค้าที่โกรธใจเย็นลง"],
["energetic","adj.","กระฉับกระเฉง มีพลัง","I'm energetic, even on early morning shifts.","ฉันกระฉับกระเฉงแม้ในกะเช้าตรู่"],
["enthusiastic","adj.","กระตือรือร้น","I'm enthusiastic about learning new things.","ฉันกระตือรือร้นที่จะเรียนรู้สิ่งใหม่"],
["flexible","adj.","ยืดหยุ่น","I'm flexible with schedules and last-minute changes.","ฉันยืดหยุ่นกับตารางงานและการเปลี่ยนแปลงกะทันหัน"],
["friendly","adj.","เป็นมิตร","A friendly greeting sets the tone for the flight.","คำทักทายที่เป็นมิตรสร้างบรรยากาศให้เที่ยวบิน"],
["genuine","adj.","จริงใจ แท้จริง","Passengers can tell when a smile is genuine.","ผู้โดยสารดูออกว่ารอยยิ้มไหนจริงใจ"],
["hard-working","adj.","ขยันทำงาน","I'm hard-working and never leave a task unfinished.","ฉันขยันและไม่เคยทิ้งงานค้าง"],
["helpful","adj.","ชอบช่วยเหลือ","The crew were very helpful with my luggage.","ลูกเรือช่วยเหลือเรื่องกระเป๋าของฉันอย่างดี"],
["honest","adj.","ซื่อสัตย์","I'm honest, even when I make a mistake.","ฉันซื่อสัตย์แม้ตอนที่ทำผิดพลาด"],
["humble","adj.","ถ่อมตัว","I stay humble and keep learning from seniors.","ฉันถ่อมตัวและเรียนรู้จากรุ่นพี่อยู่เสมอ"],
["independent","adj.","พึ่งพาตนเองได้","Living abroad made me more independent.","การอยู่ต่างประเทศทำให้ฉันพึ่งพาตนเองได้มากขึ้น"],
["kind","adj.","ใจดี","A kind word can change someone's day.","คำพูดดี ๆ เปลี่ยนวันของใครบางคนได้"],
["mature","adj.","เป็นผู้ใหญ่ มีวุฒิภาวะ","She handled the complaint in a mature way.","เธอรับมือกับคำร้องเรียนอย่างมีวุฒิภาวะ"],
["motivated","adj.","มีแรงจูงใจ","I'm highly motivated to become cabin crew.","ฉันมีแรงจูงใจสูงที่จะเป็นลูกเรือ"],
["observant","adj.","ช่างสังเกต","Crew must be observant during boarding.","ลูกเรือต้องช่างสังเกตระหว่างผู้โดยสารขึ้นเครื่อง"],
["open-minded","adj.","เปิดใจกว้าง","I'm open-minded about other cultures.","ฉันเปิดใจกว้างต่อวัฒนธรรมอื่น"],
["optimistic","adj.","มองโลกในแง่ดี","I stay optimistic when things go wrong.","ฉันมองโลกในแง่ดีแม้เมื่อมีปัญหา"],
["organised","adj.","มีระเบียบ จัดการเป็นระบบ","I'm organised and plan my tasks every morning.","ฉันเป็นระเบียบและวางแผนงานทุกเช้า"],
["outgoing","adj.","ชอบเข้าสังคม","I'm outgoing and enjoy meeting new people.","ฉันชอบเข้าสังคมและชอบพบปะคนใหม่ ๆ"],
["passionate","adj.","หลงใหล มีใจรัก","I'm passionate about customer service.","ฉันมีใจรักในงานบริการลูกค้า"],
["patient","adj.","อดทน ใจเย็น","You need to be patient with tired passengers.","คุณต้องอดทนกับผู้โดยสารที่เหนื่อยล้า"],
["polite","adj.","สุภาพ","I'm always polite, even when I have to say no.","ฉันสุภาพเสมอ แม้ตอนที่ต้องปฏิเสธ"],
["positive","adj.","คิดบวก","I keep a positive attitude under pressure.","ฉันรักษาทัศนคติเชิงบวกภายใต้ความกดดัน"],
["proactive","adj.","ทำงานเชิงรุก","I'm proactive and offer help before I'm asked.","ฉันทำงานเชิงรุกและเสนอความช่วยเหลือก่อนถูกขอ"],
["professional","adj.","เป็นมืออาชีพ","I remained professional when the guest shouted.","ฉันยังคงเป็นมืออาชีพเมื่อแขกตะโกนใส่"],
["punctual","adj.","ตรงต่อเวลา","I'm punctual and arrive fifteen minutes early.","ฉันตรงต่อเวลาและมาถึงก่อนสิบห้านาที"],
["reliable","adj.","ไว้ใจได้ เชื่อถือได้","My team knows I'm reliable.","ทีมของฉันรู้ว่าฉันไว้ใจได้"],
["resilient","adj.","ฟื้นตัวเร็ว ล้มแล้วลุกได้","I'm resilient and recover quickly from a bad day.","ฉันฟื้นตัวเร็วจากวันที่ย่ำแย่"],
["respectful","adj.","ให้ความเคารพ","I'm respectful of every culture and religion.","ฉันเคารพทุกวัฒนธรรมและศาสนา"],
["responsible","adj.","มีความรับผิดชอบ","I'm responsible for opening the shop every morning.","ฉันรับผิดชอบการเปิดร้านทุกเช้า"],
["self-motivated","adj.","กระตุ้นตัวเองได้","I'm self-motivated and don't need to be pushed.","ฉันกระตุ้นตัวเองได้โดยไม่ต้องมีใครผลักดัน"],
["sensitive","adj.","ไวต่อความรู้สึกผู้อื่น","Be sensitive to cultural differences.","ควรไวต่อความแตกต่างทางวัฒนธรรม"],
["sincere","adj.","จริงใจ","I gave her a sincere apology.","ฉันกล่าวขอโทษเธออย่างจริงใจ"],
["sociable","adj.","ชอบพบปะผู้คน","I'm sociable and comfortable talking to strangers.","ฉันชอบพบปะผู้คนและคุยกับคนแปลกหน้าได้สบาย"],
["supportive","adj.","คอยสนับสนุน","My family is very supportive of my decision.","ครอบครัวสนับสนุนการตัดสินใจของฉันมาก"],
["tactful","adj.","มีไหวพริบในการพูด","I was tactful when I refused his request.","ฉันปฏิเสธคำขอของเขาอย่างมีไหวพริบ"],
["tolerant","adj.","ใจกว้าง อดกลั้น","I'm tolerant of different opinions.","ฉันใจกว้างต่อความเห็นที่แตกต่าง"],
["trustworthy","adj.","น่าไว้วางใจ","Passengers need to feel that crew are trustworthy.","ผู้โดยสารต้องรู้สึกว่าลูกเรือน่าไว้วางใจ"],
["understanding","adj.","เข้าอกเข้าใจ","She was very understanding about the delay.","เธอเข้าอกเข้าใจเรื่องความล่าช้ามาก"],
["versatile","adj.","ทำได้หลายอย่าง","I'm versatile and can work in any position.","ฉันทำได้หลายอย่างและทำงานได้ทุกตำแหน่ง"],
["warm","adj.","อบอุ่น","Thai people are known for their warm hospitality.","คนไทยขึ้นชื่อเรื่องการต้อนรับที่อบอุ่น"],
["well-groomed","adj.","แต่งกายเรียบร้อย ดูดี","Crew must look well-groomed on every flight.","ลูกเรือต้องดูเรียบร้อยทุกเที่ยวบิน"],
["willing","adj.","เต็มใจ","I'm willing to work on weekends and holidays.","ฉันเต็มใจทำงานในวันหยุดสุดสัปดาห์และเทศกาล"],
["personality","n.","บุคลิกภาพ","My personality suits a service job.","บุคลิกของฉันเหมาะกับงานบริการ"],
["attitude","n.","ทัศนคติ","A positive attitude is more important than experience.","ทัศนคติเชิงบวกสำคัญกว่าประสบการณ์"],
["integrity","n.","ความซื่อตรง","Integrity means doing the right thing when no one is watching.","ความซื่อตรงคือการทำสิ่งที่ถูกแม้ไม่มีใครเห็น"],
["patience","n.","ความอดทน","Patience is my greatest strength.","ความอดทนคือจุดแข็งที่สุดของฉัน"],
["empathy","n.","ความเข้าอกเข้าใจ","I showed empathy by listening to her worries.","ฉันแสดงความเข้าใจด้วยการรับฟังความกังวลของเธอ"],
["stamina","n.","ความอึด ความทนทานของร่างกาย","Long-haul flights require a lot of stamina.","เที่ยวบินระยะไกลต้องใช้ความอึดมาก"],
["initiative","n.","ความคิดริเริ่ม","I took the initiative to help without being asked.","ฉันริเริ่มเข้าไปช่วยโดยไม่ต้องมีใครขอ"]
]],
["career", [
["apply","v.","สมัคร","I applied for this position last month.","ฉันสมัครตำแหน่งนี้เมื่อเดือนที่แล้ว"],
["applicant","n.","ผู้สมัคร","There were over 500 applicants at the open day.","มีผู้สมัครกว่า 500 คนในวันเปิดรับ"],
["candidate","n.","ผู้เข้าสอบสัมภาษณ์ ผู้สมัคร","I believe I'm a strong candidate.","ฉันเชื่อว่าฉันเป็นผู้สมัครที่มีคุณสมบัติดี"],
["position","n.","ตำแหน่งงาน","I'm applying for the position of cabin crew.","ฉันสมัครตำแหน่งลูกเรือ"],
["qualification","n.","คุณวุฒิ คุณสมบัติ","My qualifications include a degree and first aid training.","คุณสมบัติของฉันรวมถึงปริญญาและการอบรมปฐมพยาบาล"],
["requirement","n.","ข้อกำหนด","I meet all the requirements for this role.","ฉันมีคุณสมบัติครบตามข้อกำหนดของตำแหน่งนี้"],
["recruitment","n.","การสรรหาบุคลากร","The recruitment process has four stages.","กระบวนการสรรหามีสี่ขั้นตอน"],
["assessment","n.","การประเมิน","The assessment day includes a group activity.","วันประเมินมีกิจกรรมกลุ่มด้วย"],
["background","n.","ภูมิหลัง พื้นฐาน","My background is in hotel management.","พื้นฐานของฉันมาจากงานบริหารโรงแรม"],
["experience","n.","ประสบการณ์","I have three years of experience in customer service.","ฉันมีประสบการณ์สามปีในงานบริการลูกค้า"],
["skill","n.","ทักษะ","Communication is my strongest skill.","การสื่อสารคือทักษะที่ดีที่สุดของฉัน"],
["strength","n.","จุดแข็ง","My main strength is staying calm under pressure.","จุดแข็งหลักของฉันคือใจเย็นภายใต้ความกดดัน"],
["weakness","n.","จุดอ่อน","I'm working on my weakness in public speaking.","ฉันกำลังแก้จุดอ่อนเรื่องการพูดในที่สาธารณะ"],
["achievement","n.","ความสำเร็จ","Winning the service award is my proudest achievement.","การได้รางวัลบริการคือความสำเร็จที่ฉันภูมิใจที่สุด"],
["goal","n.","เป้าหมาย","My goal is to become a senior crew member.","เป้าหมายของฉันคือเป็นลูกเรืออาวุโส"],
["ambition","n.","ความใฝ่ฝัน ความทะเยอทะยาน","It has been my ambition since I was a child.","นี่คือความใฝ่ฝันของฉันตั้งแต่เด็ก"],
["career","n.","อาชีพ สายงาน","I want a long career with your airline.","ฉันต้องการอาชีพระยะยาวกับสายการบินของคุณ"],
["opportunity","n.","โอกาส","Thank you for giving me this opportunity.","ขอบคุณที่ให้โอกาสนี้กับฉัน"],
["challenge","n.","ความท้าทาย","I see every challenge as a chance to grow.","ฉันมองทุกความท้าทายเป็นโอกาสในการเติบโต"],
["responsibility","n.","ความรับผิดชอบ หน้าที่","My responsibilities include training new staff.","หน้าที่ของฉันรวมถึงการสอนพนักงานใหม่"],
["duty","n.","หน้าที่ เวรปฏิบัติงาน","Safety is the first duty of cabin crew.","ความปลอดภัยคือหน้าที่แรกของลูกเรือ"],
["role","n.","บทบาท","I understand the role involves more than service.","ฉันเข้าใจว่าบทบาทนี้มีมากกว่างานบริการ"],
["task","n.","งานที่ได้รับมอบหมาย","I finish every task before the end of my shift.","ฉันทำงานทุกอย่างเสร็จก่อนหมดกะ"],
["shift","n.","กะทำงาน","I'm used to working night shifts.","ฉันชินกับการทำงานกะกลางคืน"],
["schedule","n.","ตารางเวลา","I'm flexible with my schedule.","ฉันยืดหยุ่นเรื่องตารางเวลาได้"],
["deadline","n.","กำหนดส่งงาน","I have never missed a deadline.","ฉันไม่เคยส่งงานเลยกำหนด"],
["priority","n.","สิ่งที่สำคัญเป็นอันดับแรก","Passenger safety is always my top priority.","ความปลอดภัยของผู้โดยสารสำคัญที่สุดเสมอ"],
["standard","n.","มาตรฐาน","Your airline has very high service standards.","สายการบินของคุณมีมาตรฐานบริการสูงมาก"],
["reputation","n.","ชื่อเสียง","The airline has an excellent reputation worldwide.","สายการบินมีชื่อเสียงยอดเยี่ยมทั่วโลก"],
["value","n.","คุณค่า ค่านิยม","My values match the company's values.","ค่านิยมของฉันตรงกับค่านิยมของบริษัท"],
["represent","v.","เป็นตัวแทน","Crew represent the airline wherever they go.","ลูกเรือเป็นตัวแทนของสายการบินในทุกที่ที่ไป"],
["contribute","v.","มีส่วนช่วย ทำประโยชน์","I can contribute my language skills to the team.","ฉันนำทักษะภาษามาช่วยทีมได้"],
["achieve","v.","บรรลุ ทำสำเร็จ","I achieved my target three months in a row.","ฉันทำได้ตามเป้าสามเดือนติดต่อกัน"],
["improve","v.","ปรับปรุง พัฒนา","I'm improving my English every day.","ฉันพัฒนาภาษาอังกฤษทุกวัน"],
["develop","v.","พัฒนา","I want to develop my leadership skills.","ฉันอยากพัฒนาทักษะความเป็นผู้นำ"],
["gain","v.","ได้รับ สั่งสม","I gained valuable experience at the hotel.","ฉันได้ประสบการณ์ที่มีค่าจากโรงแรม"],
["manage","v.","จัดการ","I managed a team of five people.","ฉันดูแลทีมห้าคน"],
["handle","v.","รับมือ จัดการ","I can handle difficult situations calmly.","ฉันรับมือกับสถานการณ์ยาก ๆ ได้อย่างใจเย็น"],
["deal with","phr. v.","จัดการกับ","I deal with complaints every day.","ฉันจัดการกับคำร้องเรียนทุกวัน"],
["cope with","phr. v.","รับมือกับ (เรื่องยาก)","I cope with stress by exercising.","ฉันรับมือกับความเครียดด้วยการออกกำลังกาย"],
["adapt","v.","ปรับตัว","I adapt quickly to new environments.","ฉันปรับตัวเข้ากับสภาพแวดล้อมใหม่ได้เร็ว"],
["adjust","v.","ปรับเปลี่ยน","I adjusted my sleep routine for night shifts.","ฉันปรับเวลานอนให้เข้ากับกะกลางคืน"],
["overcome","v.","เอาชนะ ก้าวข้าม","I overcame my fear of public speaking.","ฉันเอาชนะความกลัวการพูดในที่สาธารณะได้"],
["prioritise","v.","จัดลำดับความสำคัญ","I prioritise urgent tasks first.","ฉันทำงานเร่งด่วนก่อน"],
["organise","v.","จัดระเบียบ จัดการ","I organised a charity event at university.","ฉันจัดงานการกุศลสมัยเรียนมหาวิทยาลัย"],
["multitask","v.","ทำหลายอย่างพร้อมกัน","I can multitask during busy hours.","ฉันทำหลายอย่างพร้อมกันได้ในชั่วโมงเร่งด่วน"],
["train","v.","ฝึกอบรม","I trained five new employees last year.","ฉันฝึกพนักงานใหม่ห้าคนเมื่อปีที่แล้ว"],
["commit","v.","ผูกมัด ทุ่มเท","I'm ready to commit to this career.","ฉันพร้อมทุ่มเทให้อาชีพนี้"],
["relocate","v.","ย้ายถิ่นฐาน","I'm happy to relocate to Doha.","ฉันยินดีย้ายไปอยู่โดฮา"],
["graduate","v.","สำเร็จการศึกษา","I graduated from Chiang Mai University in 2023.","ฉันจบจากมหาวิทยาลัยเชียงใหม่ในปี 2023"],
["major","n.","วิชาเอก","My major was English for Communication.","วิชาเอกของฉันคือภาษาอังกฤษเพื่อการสื่อสาร"],
["degree","n.","ปริญญา","I hold a bachelor's degree in tourism.","ฉันจบปริญญาตรีด้านการท่องเที่ยว"],
["internship","n.","การฝึกงาน","I did my internship at an airport lounge.","ฉันฝึกงานที่เลานจ์สนามบิน"],
["employer","n.","นายจ้าง","My current employer is a five-star hotel.","นายจ้างปัจจุบันของฉันคือโรงแรมห้าดาว"],
["supervisor","n.","หัวหน้างาน","My supervisor gave me positive feedback.","หัวหน้างานให้คำติชมเชิงบวกกับฉัน"],
["promotion","n.","การเลื่อนตำแหน่ง","I received a promotion after one year.","ฉันได้เลื่อนตำแหน่งหลังทำงานหนึ่งปี"],
["full-time","adj.","เต็มเวลา","I work full-time as a receptionist.","ฉันทำงานเต็มเวลาเป็นพนักงานต้อนรับ"],
["part-time","adj.","นอกเวลา","I had a part-time job while studying.","ฉันทำงานพิเศษระหว่างเรียน"],
["hospitality","n.","การต้อนรับ งานบริการ","I have worked in hospitality for four years.","ฉันทำงานสายบริการมาสี่ปี"],
["aviation","n.","การบิน","I have always been interested in aviation.","ฉันสนใจด้านการบินมาตลอด"],
["industry","n.","อุตสาหกรรม","The airline industry is growing fast in Asia.","อุตสาหกรรมการบินเติบโตเร็วในเอเชีย"],
["passion","n.","ความหลงใหล","Serving people is my passion.","การบริการผู้คนคือสิ่งที่ฉันหลงใหล"],
["motivation","n.","แรงจูงใจ","My motivation comes from making people happy.","แรงจูงใจของฉันมาจากการทำให้คนมีความสุข"],
["commitment","n.","ความมุ่งมั่นผูกพัน","This job requires a high level of commitment.","งานนี้ต้องการความมุ่งมั่นสูง"],
["performance","n.","ผลการปฏิบัติงาน","My performance review was excellent.","ผลประเมินการทำงานของฉันดีเยี่ยม"],
["reference","n.","บุคคลอ้างอิง","My manager is happy to be my reference.","ผู้จัดการยินดีเป็นบุคคลอ้างอิงให้ฉัน"],
["probation","n.","ช่วงทดลองงาน","I passed my probation in three months.","ฉันผ่านทดลองงานในสามเดือน"],
["contract","n.","สัญญาจ้าง","I understand the contract is for three years.","ฉันเข้าใจว่าสัญญามีระยะเวลาสามปี"],
["grooming","n.","การดูแลบุคลิกและการแต่งกาย","Grooming standards are strict for cabin crew.","มาตรฐานการแต่งกายของลูกเรือเข้มงวด"],
["uniform","n.","เครื่องแบบ","I would be proud to wear your uniform.","ฉันจะภูมิใจที่ได้สวมเครื่องแบบของคุณ"]
]],
["service", [
["customer service","n.","การบริการลูกค้า","I have four years of customer service experience.","ฉันมีประสบการณ์บริการลูกค้าสี่ปี"],
["passenger","n.","ผู้โดยสาร","Every passenger deserves the same respect.","ผู้โดยสารทุกคนควรได้รับความเคารพเท่ากัน"],
["guest","n.","แขก ลูกค้า","I greet every guest by name.","ฉันทักทายแขกทุกคนด้วยชื่อ"],
["complaint","n.","คำร้องเรียน","I handled the complaint calmly.","ฉันจัดการคำร้องเรียนอย่างใจเย็น"],
["complain","v.","บ่น ร้องเรียน","A passenger complained about the noise.","ผู้โดยสารคนหนึ่งร้องเรียนเรื่องเสียงดัง"],
["apologise","v.","ขอโทษ","I apologised for the inconvenience.","ฉันขอโทษสำหรับความไม่สะดวก"],
["apology","n.","คำขอโทษ","Please accept my sincere apology.","โปรดรับคำขอโทษจากใจของฉัน"],
["inconvenience","n.","ความไม่สะดวก","We apologise for any inconvenience caused.","ขออภัยในความไม่สะดวกที่เกิดขึ้น"],
["assist","v.","ช่วยเหลือ","May I assist you with your bag?","ให้ฉันช่วยเรื่องกระเป๋าไหมคะ"],
["assistance","n.","ความช่วยเหลือ","Please press the call button if you need assistance.","หากต้องการความช่วยเหลือโปรดกดปุ่มเรียก"],
["request","n.","คำขอ","I'll do my best to meet your request.","ฉันจะพยายามทำตามคำขอของคุณอย่างเต็มที่"],
["offer","v.","เสนอ","I offered her a blanket and some water.","ฉันเสนอผ้าห่มและน้ำให้เธอ"],
["provide","v.","จัดหาให้ มอบให้","We provide special meals on request.","เราจัดอาหารพิเศษให้เมื่อมีการขอ"],
["serve","v.","ให้บริการ เสิร์ฟ","We will serve dinner shortly after take-off.","เราจะเสิร์ฟอาหารเย็นหลังเครื่องขึ้นไม่นาน"],
["greet","v.","ทักทาย","I greet every passenger with a smile.","ฉันทักทายผู้โดยสารทุกคนด้วยรอยยิ้ม"],
["welcome","v.","ต้อนรับ","We welcome you onboard this flight to Tokyo.","ขอต้อนรับสู่เที่ยวบินนี้สู่โตเกียว"],
["satisfy","v.","ทำให้พอใจ","I always try to satisfy the customer's needs.","ฉันพยายามตอบสนองความต้องการของลูกค้าเสมอ"],
["satisfaction","n.","ความพึงพอใจ","Customer satisfaction is my main goal.","ความพึงพอใจของลูกค้าคือเป้าหมายหลักของฉัน"],
["expectation","n.","ความคาดหวัง","I try to exceed every guest's expectations.","ฉันพยายามทำให้เกินความคาดหวังของแขกทุกคน"],
["exceed","v.","เกิน ทำได้มากกว่า","Our service exceeded what she expected.","บริการของเราเกินกว่าที่เธอคาดไว้"],
["go the extra mile","idiom","ทำเกินกว่าหน้าที่","I always go the extra mile for my customers.","ฉันทำเกินหน้าที่เพื่อลูกค้าเสมอ"],
["above and beyond","idiom","เกินความคาดหมาย","She went above and beyond to help the family.","เธอช่วยเหลือครอบครัวนั้นเกินความคาดหมาย"],
["resolve","v.","แก้ไขให้จบ","I resolved the issue within ten minutes.","ฉันแก้ปัญหาได้ภายในสิบนาที"],
["solution","n.","ทางออก วิธีแก้","I offered him two possible solutions.","ฉันเสนอทางออกให้เขาสองทาง"],
["alternative","n.","ทางเลือกอื่น","I suggested an alternative when the chicken ran out.","ฉันเสนอทางเลือกอื่นเมื่อไก่หมด"],
["compensate","v.","ชดเชย","The airline compensated him for the delay.","สายการบินชดเชยให้เขาสำหรับความล่าช้า"],
["compensation","n.","ค่าชดเชย","She asked for compensation for her damaged bag.","เธอขอค่าชดเชยสำหรับกระเป๋าที่เสียหาย"],
["refund","n.","เงินคืน","The customer requested a full refund.","ลูกค้าขอเงินคืนเต็มจำนวน"],
["reassure","v.","ทำให้อุ่นใจ","I reassured the nervous passenger during turbulence.","ฉันปลอบผู้โดยสารที่กังวลให้อุ่นใจช่วงตกหลุมอากาศ"],
["comfort","n.","ความสะดวกสบาย","Your comfort and safety are important to us.","ความสบายและความปลอดภัยของคุณสำคัญสำหรับเรา"],
["comfortable","adj.","สบาย","Are you comfortable in your seat?","คุณนั่งสบายดีไหมคะ"],
["upset","adj.","ไม่พอใจ เสียใจ","The guest was upset about the wrong order.","แขกไม่พอใจเรื่องออร์เดอร์ผิด"],
["frustrated","adj.","หงุดหงิด คับข้องใจ","He was frustrated by the long wait.","เขาหงุดหงิดเพราะรอนาน"],
["demanding","adj.","เรียกร้องมาก เอาใจยาก","I enjoy the challenge of demanding customers.","ฉันสนุกกับความท้าทายของลูกค้าที่เอาใจยาก"],
["rude","adj.","หยาบคาย","I stay polite even when someone is rude.","ฉันยังสุภาพแม้อีกฝ่ายจะหยาบคาย"],
["calm down","phr. v.","ทำให้ใจเย็นลง","I helped the angry customer calm down.","ฉันช่วยให้ลูกค้าที่โกรธใจเย็นลง"],
["listen","v.","รับฟัง","First, I listen without interrupting.","อันดับแรกฉันรับฟังโดยไม่ขัดจังหวะ"],
["acknowledge","v.","รับทราบ ยอมรับ","I acknowledged her feelings before offering help.","ฉันรับรู้ความรู้สึกของเธอก่อนจะเสนอความช่วยเหลือ"],
["anticipate","v.","คาดการณ์ล่วงหน้า","Good crew anticipate what passengers need.","ลูกเรือที่ดีคาดการณ์ความต้องการของผู้โดยสารได้"],
["attend to","phr. v.","ดูแล เอาใจใส่","I'll attend to you in just a moment.","อีกสักครู่ฉันจะมาดูแลคุณ"],
["look after","phr. v.","ดูแล","We look after children travelling alone.","เราดูแลเด็กที่เดินทางคนเดียว"],
["take care of","phr. v.","ดูแล จัดการให้","Don't worry, I'll take care of it.","ไม่ต้องกังวล ฉันจะจัดการให้"],
["follow up","phr. v.","ติดตามผล","I followed up to make sure she was happy.","ฉันติดตามผลเพื่อให้แน่ใจว่าเธอพอใจ"],
["feedback","n.","คำติชม ความคิดเห็น","I welcome feedback from customers.","ฉันยินดีรับคำติชมจากลูกค้า"],
["compliment","n.","คำชม","I received a written compliment from a guest.","ฉันได้รับคำชมเป็นลายลักษณ์อักษรจากแขก"],
["preference","n.","ความชอบ สิ่งที่เลือก","I remember my regular customers' preferences.","ฉันจำความชอบของลูกค้าประจำได้"],
["special request","n.","คำขอพิเศษ","Do you have any special requests for your meal?","คุณมีคำขอพิเศษสำหรับอาหารไหมคะ"],
["personalised","adj.","เฉพาะบุคคล","Passengers appreciate personalised service.","ผู้โดยสารชื่นชมบริการที่ใส่ใจเฉพาะบุคคล"],
["attention","n.","ความสนใจ ความใส่ใจ","I give every customer my full attention.","ฉันให้ความใส่ใจลูกค้าทุกคนเต็มที่"],
["impression","n.","ความประทับใจ","The first impression happens at the aircraft door.","ความประทับใจแรกเกิดขึ้นที่ประตูเครื่องบิน"],
["loyal","adj.","ภักดี จงรักภักดี","Good service creates loyal customers.","บริการที่ดีสร้างลูกค้าที่ภักดี"],
["frequent flyer","n.","ผู้โดยสารที่เดินทางบ่อย สมาชิกสะสมไมล์","Frequent flyers expect consistent service.","ผู้โดยสารขาประจำคาดหวังบริการที่สม่ำเสมอ"],
["premium","adj.","ระดับพรีเมียม","I hope to work in the premium cabins one day.","ฉันหวังว่าวันหนึ่งจะได้ทำงานในห้องโดยสารพรีเมียม"],
["upgrade","n.","การเลื่อนชั้นที่นั่ง","He asked for a free upgrade to business class.","เขาขอเลื่อนชั้นไปชั้นธุรกิจฟรี"],
["policy","n.","นโยบาย","I explained the company policy politely.","ฉันอธิบายนโยบายบริษัทอย่างสุภาพ"],
["exception","n.","ข้อยกเว้น","I'm afraid we can't make an exception.","เกรงว่าเราทำข้อยกเว้นให้ไม่ได้"],
["available","adj.","ว่าง มีให้บริการ","I'm sorry, that option is no longer available.","ขออภัย ตัวเลือกนั้นหมดแล้ว"],
["immediately","adv.","ทันที","I'll bring it to you immediately.","ฉันจะนำมาให้คุณทันที"],
["certainly","adv.","ได้เลย แน่นอน","Certainly, I'll be right back with your water.","ได้เลยค่ะ เดี๋ยวฉันนำน้ำมาให้"],
["pleasure","n.","ความยินดี","It's my pleasure to help you.","ยินดีที่ได้ช่วยเหลือค่ะ"],
["appreciate","v.","ซาบซึ้ง ขอบคุณ","We appreciate your patience.","ขอบคุณที่อดทนรอ"],
["unfortunately","adv.","น่าเสียดายที่","Unfortunately, we have run out of the beef option.","น่าเสียดายที่เมนูเนื้อหมดแล้ว"],
["misunderstanding","n.","ความเข้าใจผิด","There was a misunderstanding about the booking.","มีความเข้าใจผิดเรื่องการจอง"],
["sympathise","v.","เห็นใจ","I sympathise with how you feel.","ฉันเห็นใจในความรู้สึกของคุณ"],
["defuse","v.","คลี่คลาย (ความตึงเครียด)","A calm voice helps defuse a tense situation.","น้ำเสียงที่สงบช่วยคลี่คลายสถานการณ์ตึงเครียด"],
["tense","adj.","ตึงเครียด","The atmosphere became tense after the delay.","บรรยากาศตึงเครียดขึ้นหลังเที่ยวบินล่าช้า"],
["genuine smile","n.","รอยยิ้มจริงใจ","A genuine smile is part of the uniform.","รอยยิ้มจริงใจคือส่วนหนึ่งของเครื่องแบบ"],
["eye contact","n.","การสบตา","I keep eye contact when I speak to passengers.","ฉันสบตาเวลาพูดกับผู้โดยสาร"],
["body language","n.","ภาษากาย","Open body language makes people feel welcome.","ภาษากายที่เปิดรับทำให้คนรู้สึกได้รับการต้อนรับ"],
["tone of voice","n.","น้ำเสียง","I keep my tone of voice soft and steady.","ฉันรักษาน้ำเสียงให้นุ่มและมั่นคง"]
]],
["team", [
["teamwork","n.","การทำงานเป็นทีม","Teamwork is essential on every flight.","การทำงานเป็นทีมจำเป็นในทุกเที่ยวบิน"],
["team player","n.","คนที่ทำงานเป็นทีมได้ดี","I'm a team player who supports my colleagues.","ฉันเป็นคนทำงานเป็นทีมที่คอยช่วยเพื่อนร่วมงาน"],
["colleague","n.","เพื่อนร่วมงาน","My colleagues come from many countries.","เพื่อนร่วมงานของฉันมาจากหลายประเทศ"],
["cooperate","v.","ร่วมมือ","We cooperated to finish the service on time.","เราร่วมมือกันเพื่อให้บริการเสร็จทันเวลา"],
["collaborate","v.","ทำงานร่วมกัน","I collaborated with the kitchen to solve the problem.","ฉันทำงานร่วมกับครัวเพื่อแก้ปัญหา"],
["support","v.","สนับสนุน ช่วยเหลือ","We support each other during busy shifts.","เราช่วยเหลือกันในกะที่ยุ่ง"],
["communicate","v.","สื่อสาร","I communicate clearly and politely.","ฉันสื่อสารอย่างชัดเจนและสุภาพ"],
["communication","n.","การสื่อสาร","Good communication prevents mistakes.","การสื่อสารที่ดีป้องกันความผิดพลาด"],
["conflict","n.","ความขัดแย้ง","I solved the conflict by talking privately.","ฉันแก้ความขัดแย้งด้วยการคุยกันเป็นการส่วนตัว"],
["disagree","v.","ไม่เห็นด้วย","Even when we disagree, I stay respectful.","แม้ไม่เห็นด้วย ฉันก็ยังให้ความเคารพ"],
["compromise","n.","การประนีประนอม","We reached a compromise that worked for both of us.","เราหาทางประนีประนอมที่ลงตัวทั้งสองฝ่าย"],
["respect","v.","เคารพ","I respect my seniors and follow their instructions.","ฉันเคารพรุ่นพี่และทำตามคำแนะนำ"],
["trust","n.","ความไว้วางใจ","Trust between crew members saves time in emergencies.","ความไว้ใจระหว่างลูกเรือช่วยประหยัดเวลาในเหตุฉุกเฉิน"],
["leadership","n.","ภาวะผู้นำ","I showed leadership when my supervisor was absent.","ฉันแสดงภาวะผู้นำตอนที่หัวหน้าไม่อยู่"],
["delegate","v.","มอบหมายงาน","I learned to delegate instead of doing everything myself.","ฉันเรียนรู้ที่จะมอบหมายงานแทนการทำเองทั้งหมด"],
["brief","v.","บรรยายสรุปก่อนเริ่มงาน","The purser briefs the crew before each flight.","หัวหน้าลูกเรือบรรยายสรุปให้ลูกเรือก่อนทุกเที่ยวบิน"],
["briefing","n.","การประชุมสรุปก่อนบิน","We discuss safety in the pre-flight briefing.","เราคุยเรื่องความปลอดภัยในการประชุมก่อนบิน"],
["instruction","n.","คำสั่ง คำแนะนำ","I follow instructions carefully.","ฉันทำตามคำสั่งอย่างระมัดระวัง"],
["report","v.","รายงาน","I reported the problem to my supervisor at once.","ฉันรายงานปัญหาให้หัวหน้าทราบทันที"],
["inform","v.","แจ้งให้ทราบ","I informed the senior crew about the situation.","ฉันแจ้งสถานการณ์ให้ลูกเรืออาวุโสทราบ"],
["clarify","v.","ทำให้ชัดเจน","I asked a question to clarify the task.","ฉันถามเพื่อให้งานชัดเจนขึ้น"],
["confirm","v.","ยืนยัน","Could you confirm your seat number, please?","ช่วยยืนยันหมายเลขที่นั่งด้วยค่ะ"],
["coordinate","v.","ประสานงาน","I coordinated with three departments for the event.","ฉันประสานงานกับสามแผนกสำหรับงานนั้น"],
["contribution","n.","การมีส่วนร่วม ผลงานที่ช่วยทีม","Everyone's contribution matters in a team.","การมีส่วนร่วมของทุกคนสำคัญต่อทีม"],
["cover","v.","ทำงานแทน","I covered my colleague's shift when she was sick.","ฉันทำงานแทนเพื่อนตอนที่เธอป่วย"],
["help out","phr. v.","ช่วยงาน","I help out wherever the team needs me.","ฉันช่วยงานทุกจุดที่ทีมต้องการ"],
["get along with","phr. v.","เข้ากันได้กับ","I get along with people of all ages.","ฉันเข้ากับคนทุกวัยได้"],
["rely on","phr. v.","พึ่งพา","My team can rely on me.","ทีมพึ่งพาฉันได้"],
["hand over","phr. v.","ส่งมอบงาน","I hand over clear notes to the next shift.","ฉันส่งมอบบันทึกที่ชัดเจนให้กะถัดไป"],
["speak up","phr. v.","กล้าพูด กล้าท้วง","I speak up when I see a safety risk.","ฉันกล้าพูดเมื่อเห็นความเสี่ยงด้านความปลอดภัย"],
["point out","phr. v.","ชี้ให้เห็น","I politely pointed out the mistake.","ฉันชี้ข้อผิดพลาดอย่างสุภาพ"],
["multicultural","adj.","หลากวัฒนธรรม","I enjoy working in a multicultural team.","ฉันชอบทำงานในทีมหลากวัฒนธรรม"],
["diversity","n.","ความหลากหลาย","Diversity makes a team stronger.","ความหลากหลายทำให้ทีมแข็งแกร่งขึ้น"],
["nationality","n.","สัญชาติ","Your crew come from over 100 nationalities.","ลูกเรือของคุณมาจากกว่า 100 สัญชาติ"],
["culture","n.","วัฒนธรรม","I love learning about other cultures.","ฉันชอบเรียนรู้วัฒนธรรมอื่น"],
["language barrier","n.","อุปสรรคทางภาษา","I used gestures to overcome the language barrier.","ฉันใช้ท่าทางเพื่อข้ามอุปสรรคทางภาษา"],
["senior","n.","รุ่นพี่ ผู้อาวุโสกว่า","I asked my senior for advice.","ฉันขอคำแนะนำจากรุ่นพี่"],
["junior","n.","รุ่นน้อง ผู้มีอายุงานน้อยกว่า","I helped the juniors learn the system.","ฉันช่วยรุ่นน้องเรียนรู้ระบบ"],
["hierarchy","n.","ลำดับชั้นการบังคับบัญชา","I understand the hierarchy onboard an aircraft.","ฉันเข้าใจลำดับการบังคับบัญชาบนเครื่องบิน"],
["authority","n.","อำนาจ ผู้มีอำนาจ","The captain has final authority onboard.","กัปตันมีอำนาจตัดสินใจสูงสุดบนเครื่อง"],
["harmony","n.","ความกลมเกลียว","I try to keep harmony in the team.","ฉันพยายามรักษาความกลมเกลียวในทีม"],
["morale","n.","ขวัญกำลังใจ","A positive attitude lifts team morale.","ทัศนคติเชิงบวกช่วยยกขวัญกำลังใจของทีม"],
["constructive","adj.","สร้างสรรค์ มีประโยชน์","I give constructive feedback, not criticism.","ฉันให้คำติชมเชิงสร้างสรรค์ ไม่ใช่การตำหนิ"],
["criticism","n.","คำวิจารณ์","I accept criticism and learn from it.","ฉันยอมรับคำวิจารณ์และเรียนรู้จากมัน"],
["interrupt","v.","ขัดจังหวะ","I never interrupt when someone is speaking.","ฉันไม่ขัดจังหวะเวลาคนอื่นพูด"],
["persuade","v.","โน้มน้าว","I persuaded him to return to his seat.","ฉันโน้มน้าวให้เขากลับไปที่นั่ง"],
["encourage","v.","ให้กำลังใจ ส่งเสริม","I encourage new staff to ask questions.","ฉันส่งเสริมให้พนักงานใหม่ถามคำถาม"],
["mediate","v.","ไกล่เกลี่ย","I mediated between the two passengers.","ฉันไกล่เกลี่ยระหว่างผู้โดยสารสองคน"],
["consensus","n.","ฉันทามติ ความเห็นร่วมกัน","Our group reached a consensus in five minutes.","กลุ่มของเราได้ข้อสรุปร่วมกันในห้านาที"],
["rapport","n.","ความสัมพันธ์อันดี","I build rapport quickly with new colleagues.","ฉันสร้างความสัมพันธ์ที่ดีกับเพื่อนร่วมงานใหม่ได้เร็ว"]
]]
);
